import { CommunicationPriority, WhatsAppAutomationTrigger, WhatsAppBroadcastStatus, WhatsAppConsentCategory, WhatsAppConversationStatus, WhatsAppMessageCategory, WhatsAppMessageType, WhatsAppTemplateGroup, WhatsAppTemplateStatus } from '@prisma/client';
import { z } from 'zod';

export const whatsappAccountSchema = z.object({ name: z.string().trim().min(2), businessAccountId: z.string().trim().min(3), appId: z.string().optional(), accessToken: z.string().min(8), appSecret: z.string().min(8), verifyToken: z.string().min(8), apiVersion: z.string().regex(/^v\d+\.\d+$/).default('v23.0'), tokenExpiresAt: z.coerce.date().optional(), phoneNumbers: z.array(z.object({ branchId: z.string(), phoneNumberId: z.string().min(3), displayPhoneNumber: z.string().min(8), verifiedName: z.string().optional(), qualityRating: z.string().optional(), messagingLimit: z.string().optional(), isDefault: z.boolean().default(false) })).min(1) });
export const whatsappQuerySchema = z.object({ branchId: z.string().optional(), accountId: z.string().optional(), status: z.string().optional(), assignedToId: z.string().optional(), mine: z.coerce.boolean().optional(), unassigned: z.coerce.boolean().optional(), unread: z.coerce.boolean().optional(), failed: z.coerce.boolean().optional(), search: z.string().optional() });
export const templateSchema = z.object({ accountId: z.string().optional(), branchId: z.string().optional(), name: z.string().trim().regex(/^[a-z0-9_]+$/), displayName: z.string().trim().min(2), language: z.string().trim().min(2).default('en'), category: z.nativeEnum(WhatsAppMessageCategory), group: z.nativeEnum(WhatsAppTemplateGroup), status: z.nativeEnum(WhatsAppTemplateStatus).default('DRAFT'), headerType: z.string().optional(), headerContent: z.string().optional(), body: z.string().trim().min(1), footer: z.string().optional(), buttons: z.array(z.record(z.string(), z.unknown())).optional(), variables: z.array(z.object({ position: z.number().int().positive(), key: z.string(), example: z.string().optional() })).optional(), active: z.boolean().default(true) });
export const templateUpdateSchema = templateSchema.partial();
export const conversationUpdateSchema = z.object({ assignedToId: z.string().nullable().optional(), status: z.nativeEnum(WhatsAppConversationStatus).optional(), priority: z.nativeEnum(CommunicationPriority).optional(), appointmentId: z.string().nullable().optional(), invoiceId: z.string().nullable().optional(), packageId: z.string().nullable().optional(), supportTicketId: z.string().nullable().optional() });
export const conversationStartSchema = z.object({ phoneNumberId: z.string(), mobile: z.string().min(8), contactName: z.string().optional(), personId: z.string().optional(), leadId: z.string().optional(), patientId: z.string().optional(), appointmentId: z.string().optional(), invoiceId: z.string().optional(), packageId: z.string().optional() });
export const whatsappMessageSchema = z.object({ conversationId: z.string(), templateId: z.string().optional(), type: z.nativeEnum(WhatsAppMessageType).default('TEXT'), content: z.string().optional(), mediaId: z.string().optional(), mediaUrl: z.string().url().optional(), mimeType: z.string().optional(), filename: z.string().optional(), variables: z.array(z.string()).default([]), category: z.nativeEnum(WhatsAppMessageCategory).default('SERVICE'), consentCategory: z.nativeEnum(WhatsAppConsentCategory).optional(), relatedRecordType: z.string().optional(), relatedRecordId: z.string().optional(), scheduledAt: z.coerce.date().optional(), interactivePayload: z.record(z.string(), z.unknown()).optional() }).refine((value) => value.templateId || value.content || value.mediaId || value.mediaUrl || value.interactivePayload, 'Message content, media, interactive payload, or template is required');
export const internalNoteSchema = z.object({ content: z.string().trim().min(1) });
export const consentSchema = z.object({ personId: z.string().optional(), phoneNumber: z.string().min(8), category: z.nativeEnum(WhatsAppConsentCategory), granted: z.boolean(), source: z.string().trim().min(2), consentedAt: z.coerce.date().optional(), consentTextVersion: z.string().trim().min(1), withdrawalReason: z.string().optional() });
const segmentationSchema = z.object({ branchId: z.string().optional(), leadStages: z.array(z.string()).optional(), leadSources: z.array(z.string()).optional(), treatmentInterest: z.string().optional(), campaign: z.string().optional(), patientStatuses: z.array(z.string()).optional(), lastVisitBefore: z.coerce.date().optional(), packageStatuses: z.array(z.string()).optional(), packageExpiryBefore: z.coerce.date().optional(), appointmentHistory: z.string().optional(), tags: z.array(z.string()).optional(), consentStatus: z.boolean().optional() });
export const broadcastSchema = z.object({ name: z.string().trim().min(2), accountId: z.string(), phoneNumberId: z.string(), branchId: z.string().optional(), templateId: z.string(), segmentation: segmentationSchema, variableDefaults: z.record(z.string(), z.string()).optional(), quietHoursStart: z.coerce.number().int().min(0).max(1439).default(1260), quietHoursEnd: z.coerce.number().int().min(0).max(1439).default(540), rateLimitPerMinute: z.coerce.number().int().min(1).max(1000).default(60), scheduledAt: z.coerce.date().optional() });
export const broadcastActionSchema = z.object({ status: z.nativeEnum(WhatsAppBroadcastStatus), notes: z.string().optional() });
export const automationSchema = z.object({ name: z.string().trim().min(2), trigger: z.nativeEnum(WhatsAppAutomationTrigger), branchId: z.string().optional(), templateId: z.string(), delayMinutes: z.coerce.number().int().min(0), sequenceStep: z.coerce.number().int().positive().default(1), stopConditions: z.array(z.string()).optional(), quietHoursStart: z.coerce.number().int().min(0).max(1439).default(1260), quietHoursEnd: z.coerce.number().int().min(0).max(1439).default(540), active: z.boolean().default(true) });
export const processJobsSchema = z.object({ limit: z.coerce.number().int().min(1).max(100).default(20) });

// Compatibility schemas for existing callers. Content is still resolved through a managed template.
export const whatsappBroadcastSchema = z.object({ audience: z.enum(['LEADS', 'PATIENTS', 'ALL']), message: z.string().min(1), templateName: z.string().default('broadcast') });
