ALTER TYPE "PaymentMode" ADD VALUE 'PAYMENT_GATEWAY';
ALTER TYPE "PaymentMode" ADD VALUE 'WALLET';
ALTER TYPE "PaymentMode" ADD VALUE 'OTHER';

ALTER TYPE "InvoiceStatus" ADD VALUE 'ISSUED';
ALTER TYPE "InvoiceStatus" ADD VALUE 'OVERDUE';
ALTER TYPE "InvoiceStatus" ADD VALUE 'REFUNDED';
