import crypto from 'node:crypto';
import type { Prisma, Role } from '@prisma/client';
import { Role as RoleEnum } from '@prisma/client';
import PDFDocument from 'pdfkit';
import type { z } from 'zod';
import { env } from '../config/env.js';
import { billingRepository } from '../repositories/billing.repository.js';
import { settingsRepository } from '../repositories/settings.repository.js';
import { timelineRepository } from '../repositories/timeline.repository.js';
import { HttpError } from '../utils/http-error.js';
import type { cashClosingDecisionSchema, cashClosingQuerySchema, cashClosingSchema, cashClosingSubmitSchema, collectionQuerySchema, collectionUpdateSchema, creditNoteQuerySchema, creditNoteSchema, discountDecisionSchema, estimateQuerySchema, estimateSchema, estimateStatusSchema, gatewayCallbackSchema, invoiceCancelSchema, invoiceIssueSchema, invoiceQuerySchema, invoiceSchema, packageActionSchema, packageMasterSchema, packageMasterUpdateSchema, patientPackageQuerySchema, patientPackageSchema, paymentAllocationSchema, paymentQuerySchema, paymentReverseSchema, paymentSchema, refundDecisionSchema, refundProcessSchema, refundQuerySchema, refundSchema } from '../validations/billing.validation.js';
import { accessService } from './access.service.js';
import { auditService, type AuditContext } from './audit.service.js';
import { agingBucket, assertPackageAction, calculateDocument, discountLimit, money, requiredApproval } from './billing-policy.js';

type Actor = AuditContext & { id: string; role: Role };
const billingRoles: Role[] = [RoleEnum.ADMIN, RoleEnum.RECEPTIONIST];
const managerRoles: Role[] = [RoleEnum.ADMIN];
const ownerRoles: Role[] = [RoleEnum.ADMIN];
const adminRoles: Role[] = [RoleEnum.ADMIN];

function requireBilling(actor: Actor) { if (!billingRoles.includes(actor.role)) throw new HttpError(403, 'Billing access is required'); }
function requireManager(actor: Actor) { if (!managerRoles.includes(actor.role)) throw new HttpError(403, 'Manager approval is required'); }
function requireAdmin(actor: Actor) { if (!adminRoles.includes(actor.role)) throw new HttpError(403, 'Clinic administrator access is required'); }
async function audit(actor: Actor, event: Parameters<typeof auditService.record>[1]) { const { userId, branchId, ipAddress, device, correlationId } = actor; await auditService.record({ userId, branchId, ipAddress, device, correlationId }, event); }
async function patientForBranch(patientId: string, branchId: string, actor: Actor) { const patient = await billingRepository.findPatient(patientId); if (!patient) throw new HttpError(404, 'Patient not found'); if (patient.branchId !== branchId) throw new HttpError(400, 'Patient does not belong to the selected branch'); await accessService.assertBranchAccess(actor.id, actor.role, branchId); return patient; }
async function timeline(patient: Awaited<ReturnType<typeof billingRepository.findPatient>>, actor: Actor, type: string, title: string, description?: string) { if (!patient) return; await timelineRepository.create({ personId: patient.personId ?? undefined, leadId: patient.leadId, patientId: patient.id, createdById: actor.id, type, title, description }); }

function documentLines(items: z.infer<typeof invoiceSchema>['items']) {
  if (!items?.length) return null; const totals = calculateDocument(items); return { ...totals, items: items.map((item, index) => ({ ...item, ...totals.items[index], sortOrder: item.sortOrder || (index + 1) * 10 })) };
}
function legacyLines(input: z.infer<typeof invoiceSchema>) { const subtotal = money(input.consultationFee + input.packageFee); const totalAmount = money(subtotal - input.discount + input.gstAmount); if (input.discount > subtotal) throw new HttpError(400, 'Discount cannot exceed subtotal'); return { subtotal, discount: input.discount, taxAmount: input.gstAmount, totalAmount, items: [{ type: 'CUSTOM' as const, description: input.serviceName ?? 'Itemized services', quantity: 1, unitPrice: subtotal, discount: input.discount, taxPercent: 0, taxAmount: input.gstAmount, totalAmount, sortOrder: 10 }] }; }
function approvalFor(total: { subtotal: number; discount: number }, reason: string | undefined, actor: Actor) { const percent = total.subtotal ? money(total.discount / total.subtotal * 100) : 0; if (total.discount > 0 && !reason?.trim()) throw new HttpError(400, 'A discount reason is required'); if (percent <= discountLimit(actor.role)) return undefined; return { requestedById: actor.id, discountAmount: total.discount, discountPercent: percent, reason: reason!, requiredLevel: requiredApproval(percent) }; }

function pdfBuffer(render: (doc: PDFKit.PDFDocument) => void) { return new Promise<Buffer>((resolve, reject) => { const doc = new PDFDocument({ margin: 48 }); const chunks: Buffer[] = []; doc.on('data', (chunk: Buffer) => chunks.push(chunk)); doc.on('end', () => resolve(Buffer.concat(chunks))); doc.on('error', reject); render(doc); doc.end(); }); }

export const billingService = {
  async listEstimates(query: z.infer<typeof estimateQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return billingRepository.listEstimates(query); },
  async createEstimate(input: z.infer<typeof estimateSchema>, actor: Actor) { requireBilling(actor); const patient = await patientForBranch(input.patientId, input.branchId, actor); const totals = calculateDocument(input.items); const estimate = await billingRepository.createEstimate({ estimateNo: billingRepository.nextNumber('EST'), patientId: input.patientId, branchId: input.branchId, validUntil: input.validUntil, subtotal: totals.subtotal, discount: totals.discount, taxAmount: totals.taxAmount, totalAmount: totals.totalAmount, status: input.status, notes: input.notes, terms: input.terms, createdById: actor.id }, input.items.map((item, index) => ({ ...item, ...totals.items[index], sortOrder: item.sortOrder || (index + 1) * 10 }))); await timeline(patient, actor, 'ESTIMATE_CREATED', 'Estimate created', `${estimate.estimateNo} - Rs ${estimate.totalAmount}`); await audit(actor, { action: 'ESTIMATE_CREATED', entity: 'Estimate', entityId: estimate.id, newValue: { totalAmount: totals.totalAmount, status: estimate.status } }); return estimate; },
  async updateEstimateStatus(id: string, input: z.infer<typeof estimateStatusSchema>, actor: Actor) { requireBilling(actor); const estimate = await billingRepository.findEstimate(id); if (!estimate) throw new HttpError(404, 'Estimate not found'); await accessService.assertBranchAccess(actor.id, actor.role, estimate.branchId); const allowed: Record<string, string[]> = { DRAFT: ['SENT', 'CANCELLED'], SENT: ['ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED'], ACCEPTED: ['CONVERTED', 'CANCELLED'] }; if (!allowed[estimate.status]?.includes(input.status)) throw new HttpError(409, `Estimate cannot move from ${estimate.status} to ${input.status}`); const updated = await billingRepository.updateEstimateStatus(id, input.status); await audit(actor, { action: 'ESTIMATE_STATUS_CHANGED', entity: 'Estimate', entityId: id, previousValue: { status: estimate.status }, newValue: { status: input.status } }); return updated; },
  async convertEstimate(id: string, input: z.infer<typeof invoiceIssueSchema>, actor: Actor) { requireBilling(actor); const estimate = await billingRepository.findEstimate(id); if (!estimate) throw new HttpError(404, 'Estimate not found'); if (!['SENT', 'ACCEPTED'].includes(estimate.status)) throw new HttpError(409, 'Only sent or accepted estimates can become invoices'); await accessService.assertBranchAccess(actor.id, actor.role, estimate.branchId); const settings = await settingsRepository.getOrCreate(); const totals = { subtotal: Number(estimate.subtotal), discount: Number(estimate.discount) }; const approval = approvalFor(totals, estimate.notes ?? 'Estimate discount', actor); const invoice = await billingRepository.convertEstimate(id, { invoiceNo: billingRepository.nextNumber(settings.invoicePrefix), patientId: estimate.patientId, branchId: estimate.branchId, dueDate: input.dueDate, serviceName: 'Estimate conversion', subtotal: estimate.subtotal, discount: estimate.discount, taxAmount: estimate.taxAmount, gstAmount: estimate.taxAmount, totalAmount: estimate.totalAmount, outstandingAmount: estimate.totalAmount, terms: input.terms ?? estimate.terms, notes: estimate.notes, createdById: actor.id }, estimate.items.map((item) => ({ type: item.type, description: item.description, serviceId: item.serviceId, packageMasterId: item.packageMasterId, productName: item.productName, quantity: item.quantity, unitPrice: item.unitPrice, discount: item.discount, taxPercent: item.taxPercent, taxAmount: item.taxAmount, totalAmount: item.totalAmount, sortOrder: item.sortOrder })), approval); await audit(actor, { action: 'ESTIMATE_CONVERTED', entity: 'Invoice', entityId: invoice.id, newValue: { estimateId: id, invoiceNo: invoice.invoiceNo } }); return invoice; },

  async listInvoices(query: z.infer<typeof invoiceQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); await billingRepository.markOverdue(query.branchId); return billingRepository.listInvoices(query); },
  async createInvoice(input: z.infer<typeof invoiceSchema>, actor: Actor) { requireBilling(actor); const patient = await patientForBranch(input.patientId, input.branchId, actor); const totals = documentLines(input.items) ?? legacyLines(input); const approval = approvalFor(totals, input.discountReason, actor); const settings = await settingsRepository.getOrCreate(); const invoice = await billingRepository.createInvoice({ invoiceNo: billingRepository.nextNumber(settings.invoicePrefix), patientId: input.patientId, branchId: input.branchId, dueDate: input.dueDate, serviceName: input.serviceName ?? 'Itemized services', consultationFee: input.consultationFee, packageFee: input.packageFee, subtotal: totals.subtotal, discount: totals.discount, gstAmount: totals.taxAmount, taxAmount: totals.taxAmount, totalAmount: totals.totalAmount, outstandingAmount: totals.totalAmount, discountReason: input.discountReason, notes: input.notes, terms: input.terms, createdById: actor.id }, totals.items as Prisma.InvoiceItemUncheckedCreateWithoutInvoiceInput[], approval); await timeline(patient, actor, 'INVOICE_GENERATED', 'Invoice generated', `${invoice.invoiceNo} - Rs ${invoice.totalAmount}`); await audit(actor, { action: 'INVOICE_CREATED', entity: 'Invoice', entityId: invoice.id, newValue: { totalAmount: totals.totalAmount, approvalRequired: Boolean(approval) } }); return invoice; },
  async issueInvoice(id: string, input: z.infer<typeof invoiceIssueSchema>, actor: Actor) { requireBilling(actor); const invoice = await billingRepository.findInvoice(id); if (!invoice) throw new HttpError(404, 'Invoice not found'); await accessService.assertBranchAccess(actor.id, actor.role, invoice.branchId); if (invoice.status !== 'DRAFT') throw new HttpError(409, 'Only draft invoices can be issued'); if (invoice.discountApproval && invoice.discountApproval.status !== 'APPROVED') throw new HttpError(409, 'Discount approval is required before issue'); const updated = await billingRepository.updateInvoice(id, { status: input.dueDate && input.dueDate < new Date() ? 'OVERDUE' : 'ISSUED', issuedAt: new Date(), dueDate: input.dueDate ?? invoice.dueDate, terms: input.terms ?? invoice.terms }); await audit(actor, { action: 'INVOICE_ISSUED', entity: 'Invoice', entityId: id }); return updated; },
  async cancelInvoice(id: string, input: z.infer<typeof invoiceCancelSchema>, actor: Actor) { requireManager(actor); const invoice = await billingRepository.findInvoice(id); if (!invoice) throw new HttpError(404, 'Invoice not found'); await accessService.assertBranchAccess(actor.id, actor.role, invoice.branchId); if (Number(invoice.paidAmount) > 0) throw new HttpError(409, 'Paid invoices require a refund or credit note'); const updated = await billingRepository.updateInvoice(id, { status: 'CANCELLED', cancelledAt: new Date(), cancellationReason: input.reason }); await audit(actor, { action: 'INVOICE_CANCELLED', entity: 'Invoice', entityId: id, newValue: { reason: input.reason } }); return updated; },

  async listPayments(query: z.infer<typeof paymentQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return billingRepository.listPayments(query); },
  async addPayment(input: z.infer<typeof paymentSchema>, actor: Actor, routeInvoiceId?: string) { requireBilling(actor); const branchId = input.branchId ?? (routeInvoiceId ? (await billingRepository.findInvoice(routeInvoiceId))?.branchId : undefined); if (!branchId) throw new HttpError(400, 'Payment branch is required'); const patient = await patientForBranch(input.patientId, branchId, actor); let allocations = input.allocations ?? []; if (routeInvoiceId && !allocations.length) { const invoice = await billingRepository.findInvoice(routeInvoiceId); if (!invoice) throw new HttpError(404, 'Invoice not found'); allocations = [{ invoiceId: routeInvoiceId, amount: Math.min(input.amount, Number(invoice.outstandingAmount)) }]; }
    const allocated = money(allocations.reduce((sum, item) => sum + item.amount, 0)); if (allocated > input.amount) throw new HttpError(400, 'Allocated amount cannot exceed payment amount'); for (const allocation of allocations) { const invoice = await billingRepository.findInvoice(allocation.invoiceId); if (!invoice) throw new HttpError(404, 'Allocation invoice not found'); if (invoice.patientId !== input.patientId || invoice.branchId !== branchId) throw new HttpError(400, 'Payment allocations must match patient and branch'); if (invoice.status === 'DRAFT' || invoice.status === 'CANCELLED') throw new HttpError(409, 'Payments require an issued invoice'); if (allocation.amount > Number(invoice.outstandingAmount)) throw new HttpError(409, `Allocation exceeds outstanding amount for ${invoice.invoiceNo}`); }
    const payment = await billingRepository.createPayment({ paymentNo: billingRepository.nextNumber('PAY'), patientId: input.patientId, branchId, amount: input.amount, mode: input.mode, status: input.mode === 'PAYMENT_GATEWAY' ? 'PENDING' : 'COMPLETED', paidAt: input.paidAt, reference: input.reference, notes: input.notes, collectedById: actor.id }, allocations); await timeline(patient, actor, 'PAYMENT_COLLECTED', 'Payment collected', `${payment.paymentNo} - Rs ${payment.amount}${input.amount > allocated ? ' - advance balance retained' : ''}`); await audit(actor, { action: 'PAYMENT_RECORDED', entity: 'Payment', entityId: payment.id, newValue: { amount: input.amount, allocated, mode: input.mode } }); return payment; },
  async allocatePayment(id: string, input: z.infer<typeof paymentAllocationSchema>, actor: Actor) { requireBilling(actor); const payment = await billingRepository.findPayment(id); if (!payment) throw new HttpError(404, 'Payment not found'); await accessService.assertBranchAccess(actor.id, actor.role, payment.branchId); if (payment.status !== 'COMPLETED') throw new HttpError(409, 'Only completed payments can be allocated'); const available = Number(payment.amount) - Number(payment.allocatedAmount); if (input.amount > available) throw new HttpError(409, 'Allocation exceeds unallocated payment balance'); const invoice = await billingRepository.findInvoice(input.invoiceId); if (!invoice || invoice.patientId !== payment.patientId || invoice.branchId !== payment.branchId) throw new HttpError(400, 'Invoice does not match payment patient and branch'); if (!['ISSUED', 'PARTIAL', 'OVERDUE'].includes(invoice.status)) throw new HttpError(409, 'Only issued invoices can receive allocations'); if (input.amount > Number(invoice.outstandingAmount)) throw new HttpError(409, 'Allocation exceeds invoice outstanding amount'); const result = await billingRepository.allocatePayment(id, input.invoiceId, input.amount); await audit(actor, { action: 'PAYMENT_ALLOCATED', entity: 'Payment', entityId: id, newValue: input }); return result; },
  async reversePayment(id: string, input: z.infer<typeof paymentReverseSchema>, actor: Actor) { requireManager(actor); const payment = await billingRepository.findPayment(id); if (!payment) throw new HttpError(404, 'Payment not found'); await accessService.assertBranchAccess(actor.id, actor.role, payment.branchId); if (payment.status !== 'COMPLETED') throw new HttpError(409, 'Only completed payments can be reversed'); if (payment.refunds.some((refund) => refund.status === 'PROCESSED')) throw new HttpError(409, 'A refunded payment cannot be reversed'); const reversed = await billingRepository.reversePayment(id, actor.id, input.reason); await audit(actor, { action: 'PAYMENT_REVERSED', entity: 'Payment', entityId: id, newValue: { reason: input.reason } }); return reversed; },
  async gatewayCallback(input: z.infer<typeof gatewayCallbackSchema>) { const secret = env.PAYMENT_GATEWAY_SECRET ?? env.JWT_ACCESS_SECRET; const payload = `${input.eventId}.${input.paymentNo}.${input.status}.${input.transactionReference ?? ''}`; const expected = crypto.createHmac('sha256', secret).update(payload).digest('hex'); if (input.signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(input.signature), Buffer.from(expected))) throw new HttpError(401, 'Gateway signature verification failed'); const payment = await billingRepository.findPaymentByNo(input.paymentNo); if (!payment) throw new HttpError(404, 'Payment not found'); if (payment.gatewayEventId) { if (payment.gatewayEventId === input.eventId) return payment; throw new HttpError(409, 'Payment already has a verified gateway event'); } return billingRepository.applyGatewayEvent(payment.id, input.eventId, input.status, input.transactionReference); },

  async listRefunds(query: z.infer<typeof refundQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return billingRepository.listRefunds(query); },
  async requestRefund(input: z.infer<typeof refundSchema>, actor: Actor) { requireBilling(actor); const invoice = await billingRepository.findInvoice(input.invoiceId); const payment = await billingRepository.findPayment(input.paymentId); if (!invoice || !payment) throw new HttpError(404, 'Invoice or payment not found'); if (invoice.patientId !== payment.patientId || invoice.branchId !== payment.branchId) throw new HttpError(400, 'Refund references do not match'); const allocation = payment.allocations.find((item) => item.invoiceId === invoice.id); if (!allocation) throw new HttpError(409, 'Original payment is not allocated to this invoice'); await accessService.assertBranchAccess(actor.id, actor.role, invoice.branchId); const refunded = payment.refunds.filter((item) => item.invoiceId === invoice.id && ['APPROVED', 'PROCESSED'].includes(item.status)).reduce((sum, item) => sum + Number(item.amount), 0); if (input.amount > Number(allocation.amount) - refunded) throw new HttpError(409, 'Refund exceeds the payment amount allocated to this invoice'); const refund = await billingRepository.createRefund({ refundNo: billingRepository.nextNumber('REF'), invoiceId: invoice.id, paymentId: payment.id, patientId: invoice.patientId, branchId: invoice.branchId, reason: input.reason, amount: input.amount, refundMethod: input.refundMethod, notes: input.notes, requestedById: actor.id }); await audit(actor, { action: 'REFUND_REQUESTED', entity: 'Refund', entityId: refund.id, newValue: { amount: input.amount, reason: input.reason } }); return refund; },
  async decideRefund(id: string, input: z.infer<typeof refundDecisionSchema>, actor: Actor) { requireManager(actor); const refund = await billingRepository.findRefund(id); if (!refund) throw new HttpError(404, 'Refund not found'); await accessService.assertBranchAccess(actor.id, actor.role, refund.branchId); if (refund.status !== 'PENDING') throw new HttpError(409, 'Only pending refunds can be decided'); const result = await billingRepository.decideRefund(id, input.approved, actor.id, input.notes); await audit(actor, { action: input.approved ? 'REFUND_APPROVED' : 'REFUND_REJECTED', entity: 'Refund', entityId: id, newValue: { notes: input.notes } }); return result; },
  async processRefund(id: string, input: z.infer<typeof refundProcessSchema>, actor: Actor) { requireBilling(actor); const refund = await billingRepository.findRefund(id); if (!refund) throw new HttpError(404, 'Refund not found'); await accessService.assertBranchAccess(actor.id, actor.role, refund.branchId); if (refund.status !== 'APPROVED') throw new HttpError(409, 'Refund approval is required'); const result = await billingRepository.processRefund(id, input.refundMethod, input.transactionReference); await audit(actor, { action: 'REFUND_PROCESSED', entity: 'Refund', entityId: id, newValue: input }); return result; },

  async listCreditNotes(query: z.infer<typeof creditNoteQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return billingRepository.listCreditNotes(query); },
  async createCreditNote(input: z.infer<typeof creditNoteSchema>, actor: Actor) { requireManager(actor); const invoice = await billingRepository.findInvoice(input.invoiceId); if (!invoice) throw new HttpError(404, 'Invoice not found'); await accessService.assertBranchAccess(actor.id, actor.role, invoice.branchId); if (input.amount > Number(invoice.outstandingAmount)) throw new HttpError(409, 'Credit note exceeds outstanding amount'); const note = await billingRepository.createCreditNote({ creditNoteNo: billingRepository.nextNumber('CN'), invoiceId: invoice.id, patientId: invoice.patientId, branchId: invoice.branchId, reason: input.reason, amount: input.amount, notes: input.notes, status: 'ISSUED', issuedById: actor.id, issuedAt: new Date() }); await audit(actor, { action: 'CREDIT_NOTE_ISSUED', entity: 'CreditNote', entityId: note.id, newValue: { amount: input.amount, reason: input.reason } }); return note; },
  async applyCreditNote(id: string, actor: Actor) { requireManager(actor); const note = await billingRepository.findCreditNote(id); if (!note) throw new HttpError(404, 'Credit note not found'); await accessService.assertBranchAccess(actor.id, actor.role, note.invoice.branchId); if (note.status !== 'ISSUED') throw new HttpError(409, 'Only issued credit notes can be applied'); if (Number(note.amount) > Number(note.invoice.outstandingAmount)) throw new HttpError(409, 'Credit note now exceeds the invoice outstanding amount'); const result = await billingRepository.applyCreditNote(id, actor.id); await audit(actor, { action: 'CREDIT_NOTE_APPLIED', entity: 'CreditNote', entityId: id }); return result; },

  async listDiscountApprovals(branchId: string | undefined, actor: Actor) { requireManager(actor); await accessService.assertBranchAccess(actor.id, actor.role, branchId); return billingRepository.listDiscountApprovals(branchId); },
  async decideDiscount(id: string, input: z.infer<typeof discountDecisionSchema>, actor: Actor) { requireManager(actor); const approval = await billingRepository.findDiscountApproval(id); if (!approval) throw new HttpError(404, 'Discount approval not found'); await accessService.assertBranchAccess(actor.id, actor.role, approval.invoice.branchId); if (approval.status !== 'PENDING') throw new HttpError(409, 'Discount request is already decided'); if (approval.requiredLevel === 'OWNER' && !ownerRoles.includes(actor.role)) throw new HttpError(403, 'Owner approval is required for this discount'); const result = await billingRepository.decideDiscount(id, input.approved, actor.id, input.notes); await audit(actor, { action: input.approved ? 'DISCOUNT_APPROVED' : 'DISCOUNT_REJECTED', entity: 'DiscountApproval', entityId: id, newValue: { notes: input.notes } }); return result; },

  async listOutstanding(query: z.infer<typeof collectionQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); await billingRepository.markOverdue(query.branchId); const invoices = await billingRepository.listOutstanding(query.branchId); return invoices.map((invoice) => ({ ...invoice, agingBucket: agingBucket(invoice.dueDate), agingDays: invoice.dueDate ? Math.max(0, Math.floor((Date.now() - invoice.dueDate.getTime()) / 86_400_000)) : 0 })).filter((invoice) => !query.aging || invoice.agingBucket === query.aging); },
  async updateCollection(id: string, input: z.infer<typeof collectionUpdateSchema>, actor: Actor) { requireBilling(actor); const invoice = await billingRepository.findInvoice(id); if (!invoice) throw new HttpError(404, 'Invoice not found'); await accessService.assertBranchAccess(actor.id, actor.role, invoice.branchId); const updated = await billingRepository.updateInvoice(id, input); await audit(actor, { action: 'COLLECTION_UPDATED', entity: 'Invoice', entityId: id, newValue: input as Prisma.InputJsonValue }); return updated; },

  async listPackageMasters(branchId: string | undefined, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, branchId); return billingRepository.listPackageMasters(branchId); },
  async createPackageMaster(input: z.infer<typeof packageMasterSchema>, actor: Actor) { requireAdmin(actor); await accessService.assertBranchAccess(actor.id, actor.role, input.branchId); const created = await billingRepository.createPackageMaster({ ...input, includedServices: input.includedServices, branchRestrictions: input.branchRestrictions, practitionerRestrictions: input.practitionerRestrictions }); await audit(actor, { action: 'PACKAGE_MASTER_CREATED', entity: 'PackageMaster', entityId: created.id }); return created; },
  async updatePackageMaster(id: string, input: z.infer<typeof packageMasterUpdateSchema>, actor: Actor) { requireAdmin(actor); const existing = await billingRepository.findPackageMaster(id); if (!existing) throw new HttpError(404, 'Package master not found'); await accessService.assertBranchAccess(actor.id, actor.role, existing.branchId ?? undefined); const updated = await billingRepository.updatePackageMaster(id, { ...input, includedServices: input.includedServices, branchRestrictions: input.branchRestrictions, practitionerRestrictions: input.practitionerRestrictions }); await audit(actor, { action: 'PACKAGE_MASTER_UPDATED', entity: 'PackageMaster', entityId: id }); return updated; },
  async listPatientPackages(query: z.infer<typeof patientPackageQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return billingRepository.listPatientPackages(query); },
  async purchasePackage(input: z.infer<typeof patientPackageSchema>, actor: Actor) { requireBilling(actor); const patient = await patientForBranch(input.patientId, input.branchId, actor); const master = await billingRepository.findPackageMaster(input.packageMasterId); if (!master || !master.active) throw new HttpError(404, 'Active package master not found'); if (master.branchId && master.branchId !== input.branchId) throw new HttpError(409, 'Package is restricted to another branch'); const maxDiscount = Number(master.price) * Number(master.maximumDiscountPercent) / 100; if (input.discount > maxDiscount && !managerRoles.includes(actor.role)) throw new HttpError(403, 'Package discount requires manager approval'); const taxPercent = input.taxPercent ?? Number(master.taxPercent); const taxAmount = money((Number(master.price) - input.discount) * taxPercent / 100); const amount = money(Number(master.price) - input.discount + taxAmount); if (input.paidAmount > amount) throw new HttpError(400, 'Package paid amount cannot exceed its total; record excess as an advance payment'); const startDate = input.startDate ?? new Date(); const purchased = await billingRepository.purchasePackage({ patientId: input.patientId, branchId: input.branchId, packageMasterId: master.id, name: master.name, purchaseDate: new Date(), startDate, expiryDate: new Date(startDate.getTime() + master.validityDays * 86_400_000), totalSessions: master.totalSessions, amount, taxAmount, discount: input.discount, paidAmount: input.paidAmount, outstandingAmount: Math.max(0, amount - input.paidAmount), status: input.paidAmount > 0 ? 'ACTIVE' : 'PENDING', notes: input.notes }, actor.id); await timeline(patient, actor, 'PACKAGE_PURCHASED', 'Package purchased', `${master.name} - ${master.totalSessions} sessions`); await audit(actor, { action: 'PATIENT_PACKAGE_PURCHASED', entity: 'TreatmentPackage', entityId: purchased.id, newValue: { packageMasterId: master.id, amount, taxPercent } }); return purchased; },
  async packageAction(id: string, input: z.infer<typeof packageActionSchema>, actor: Actor) { requireBilling(actor); const current = await billingRepository.findPatientPackage(id); if (!current) throw new HttpError(404, 'Patient package not found'); await accessService.assertBranchAccess(actor.id, actor.role, current.branchId); const remaining = current.totalSessions - current.completedSessions - current.reservedSessions; assertPackageAction(current.status, input.action, remaining, input.sessions); if (input.action === 'SESSION_REVERSAL' && input.sessions > current.completedSessions) throw new HttpError(409, 'Cannot reverse more sessions than consumed'); if (input.action === 'EXTENSION' && !input.extensionDays) throw new HttpError(400, 'Extension days are required'); if (['REFUND', 'TRANSFER', 'EXPIRY_ADJUSTMENT'].includes(input.action)) requireManager(actor); let transferMetadata: Prisma.InputJsonValue | undefined = input.metadata as Prisma.InputJsonValue | undefined; if (input.action === 'TRANSFER') { if (!input.targetPatientId || !input.targetBranchId) throw new HttpError(400, 'Transfer target patient and branch are required'); const target = await patientForBranch(input.targetPatientId, input.targetBranchId, actor); transferMetadata = { ...(input.metadata ?? {}), fromPatientId: current.patientId, fromBranchId: current.branchId, toPatientId: target.id, toBranchId: target.branchId }; } const updated = await billingRepository.applyPackageAction(id, input.action, { ...input, metadata: transferMetadata }, actor.id); await audit(actor, { action: `PACKAGE_${input.action}`, entity: 'TreatmentPackage', entityId: id, newValue: { sessions: input.sessions, notes: input.notes } }); return updated; },

  async listCashClosings(query: z.infer<typeof cashClosingQuerySchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return billingRepository.listCashClosings(query); },
  async createCashClosing(input: z.infer<typeof cashClosingSchema>, actor: Actor) { requireBilling(actor); await accessService.assertBranchAccess(actor.id, actor.role, input.branchId); const start = new Date(input.closingDate); start.setHours(0, 0, 0, 0); const end = new Date(start.getTime() + 86_400_000); const [payments, refunds] = await Promise.all([billingRepository.paymentTotals(input.branchId, start, end), billingRepository.refundTotal(input.branchId, start, end)]); const byMode = Object.fromEntries(payments.map((item) => [item.mode, Number(item._sum.amount ?? 0)])); const refundAmount = Number(refunds._sum.amount ?? 0); const expected = money(input.openingCash + (byMode.CASH ?? 0) - refundAmount - input.expenses); const closing = await billingRepository.createCashClosing({ branchId: input.branchId, closingDate: start, openingCash: input.openingCash, cashCollected: byMode.CASH ?? 0, cardCollected: byMode.CARD ?? 0, upiCollected: byMode.UPI ?? 0, bankTransferCollected: byMode.BANK_TRANSFER ?? 0, otherCollected: (byMode.WALLET ?? 0) + (byMode.PAYMENT_GATEWAY ?? 0) + (byMode.OTHER ?? 0), refunds: refundAmount, expenses: input.expenses, expectedClosingCash: expected, actualClosingCash: input.actualClosingCash, difference: input.actualClosingCash === undefined ? undefined : money(input.actualClosingCash - expected), closingNotes: input.closingNotes }); await audit(actor, { action: 'CASH_CLOSING_CREATED', entity: 'DailyCashClosing', entityId: closing.id, newValue: { expectedClosingCash: expected } }); return closing; },
  async submitCashClosing(id: string, input: z.infer<typeof cashClosingSubmitSchema>, actor: Actor) { requireBilling(actor); const closing = await billingRepository.findCashClosing(id); if (!closing) throw new HttpError(404, 'Cash closing not found'); await accessService.assertBranchAccess(actor.id, actor.role, closing.branchId); if (!['DRAFT', 'REJECTED'].includes(closing.status)) throw new HttpError(409, 'Cash closing cannot be submitted'); const updated = await billingRepository.updateCashClosing(id, { status: 'SUBMITTED', actualClosingCash: input.actualClosingCash, difference: money(input.actualClosingCash - Number(closing.expectedClosingCash)), closingNotes: input.closingNotes, submittedById: actor.id, submittedAt: new Date(), rejectionReason: null }); await audit(actor, { action: 'CASH_CLOSING_SUBMITTED', entity: 'DailyCashClosing', entityId: id }); return updated; },
  async decideCashClosing(id: string, input: z.infer<typeof cashClosingDecisionSchema>, actor: Actor) { requireManager(actor); const closing = await billingRepository.findCashClosing(id); if (!closing) throw new HttpError(404, 'Cash closing not found'); await accessService.assertBranchAccess(actor.id, actor.role, closing.branchId); if (closing.status !== 'SUBMITTED') throw new HttpError(409, 'Only submitted cash closings can be reviewed'); const updated = await billingRepository.updateCashClosing(id, { status: input.approved ? 'APPROVED' : 'REJECTED', approvedById: input.approved ? actor.id : undefined, approvedAt: input.approved ? new Date() : undefined, rejectionReason: input.approved ? null : input.notes }); await audit(actor, { action: input.approved ? 'CASH_CLOSING_APPROVED' : 'CASH_CLOSING_REJECTED', entity: 'DailyCashClosing', entityId: id, newValue: { notes: input.notes } }); return updated; },

  async getInvoicePdf(id: string, actor: Actor) {
    requireBilling(actor);
    const invoice = await billingRepository.findInvoice(id);
    if (!invoice) throw new HttpError(404, 'Invoice not found');
    await accessService.assertBranchAccess(actor.id, actor.role, invoice.branchId);
    const settings = await settingsRepository.getOrCreate();
    await audit(actor, { action: 'INVOICE_PDF_VIEWED', entity: 'Invoice', entityId: id });
    return pdfBuffer((doc) => {
      const hasGst = Number(invoice.taxAmount) > 0;
      const brand = settings.clinicName || 'Revive Clinic';
      const legalName = settings.legalName || brand;
      const address = settings.businessAddress || invoice.branch.address || invoice.branch.name;
      const phone = settings.businessPhone || invoice.branch.phone || '';
      const line = (y: number) => doc.moveTo(48, y).lineTo(548, y).strokeColor('#d8c7ca').lineWidth(0.7).stroke();
      const amount = (value: unknown) => `Rs ${Number(value ?? 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

      doc.font('Helvetica-Bold').fontSize(22).fillColor('#a51d2d').text(brand, 48, 42, { width: 320 });
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#241719').text(hasGst ? 'TAX INVOICE' : 'INVOICE', 380, 45, { width: 168, align: 'right' });
      doc.font('Helvetica').fontSize(9).fillColor('#5f5053').text(legalName, 48, 72).text(address, 48, 86, { width: 320 });
      if (phone) doc.text(`Phone: ${phone}`, 48, 112);
      if (settings.clinicEmail) doc.text(`Email: ${settings.clinicEmail}`, 48, 126);
      if (hasGst && settings.gstNumber) doc.font('Helvetica-Bold').text(`GSTIN: ${settings.gstNumber}`, 380, 72, { width: 168, align: 'right' });
      if (settings.registrationNumber) doc.font('Helvetica').text(`Registration: ${settings.registrationNumber}`, 380, 88, { width: 168, align: 'right' });
      line(148);

      doc.font('Helvetica-Bold').fontSize(10).fillColor('#241719').text('BILL TO', 48, 166);
      doc.font('Helvetica').fontSize(10).text(invoice.patient.fullName, 48, 184).fontSize(9).fillColor('#5f5053').text(`Patient No: ${invoice.patient.patientNo}`, 48, 200).text(`Branch: ${invoice.branch.name}`, 48, 216);
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#241719').text('Invoice number', 350, 166).text('Invoice date', 350, 188).text('Status', 350, 210);
      doc.font('Helvetica').fillColor('#5f5053').text(invoice.invoiceNo, 440, 166, { width: 108, align: 'right' }).text(invoice.invoiceDate.toLocaleDateString('en-IN'), 440, 188, { width: 108, align: 'right' }).text(invoice.status.replaceAll('_', ' '), 440, 210, { width: 108, align: 'right' });

      let y = 256;
      doc.rect(48, y, 500, 26).fill('#a51d2d');
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text('DESCRIPTION', 56, y + 9, { width: 210 }).text('QTY', 276, y + 9, { width: 36, align: 'right' }).text('RATE', 320, y + 9, { width: 68, align: 'right' }).text('DISC.', 396, y + 9, { width: 52, align: 'right' }).text(hasGst ? 'GST' : 'TAX', 454, y + 9, { width: 38, align: 'right' }).text('AMOUNT', 496, y + 9, { width: 46, align: 'right' });
      y += 26;
      invoice.items.forEach((item, index) => {
        const rowHeight = Math.max(30, doc.heightOfString(item.description, { width: 210 }) + 14);
        if (y + rowHeight > 650) { doc.addPage(); y = 56; }
        if (index % 2 === 0) doc.rect(48, y, 500, rowHeight).fill('#faf6f6');
        doc.font('Helvetica').fontSize(8.5).fillColor('#241719').text(item.description, 56, y + 8, { width: 210 }).text(String(item.quantity), 276, y + 8, { width: 36, align: 'right' }).text(amount(item.unitPrice).replace('Rs ', ''), 320, y + 8, { width: 68, align: 'right' }).text(amount(item.discount).replace('Rs ', ''), 396, y + 8, { width: 52, align: 'right' }).text(hasGst ? `${Number(item.taxPercent)}%` : '0%', 454, y + 8, { width: 38, align: 'right' }).text(amount(item.totalAmount).replace('Rs ', ''), 496, y + 8, { width: 46, align: 'right' });
        y += rowHeight;
      });
      line(y);
      y += 16;
      const totalRow = (title: string, value: unknown, bold = false) => { doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(bold ? 11 : 9).fillColor('#241719').text(title, 350, y, { width: 90 }).text(amount(value), 440, y, { width: 108, align: 'right' }); y += bold ? 20 : 16; };
      totalRow('Subtotal', invoice.subtotal);
      totalRow('Discount', invoice.discount);
      if (hasGst) { totalRow('CGST', Number(invoice.taxAmount) / 2); totalRow('SGST', Number(invoice.taxAmount) / 2); }
      totalRow('Grand total', invoice.totalAmount, true);
      totalRow('Paid', invoice.paidAmount);
      totalRow('Balance due', invoice.outstandingAmount, true);

      const notesY = Math.max(y + 8, 570);
      if (invoice.notes) doc.font('Helvetica-Bold').fontSize(9).text('Notes', 48, notesY).font('Helvetica').fontSize(8.5).fillColor('#5f5053').text(invoice.notes, 48, notesY + 14, { width: 280, height: 34, ellipsis: true });
      if (invoice.terms || settings.invoiceTerms) doc.font('Helvetica-Bold').fontSize(9).fillColor('#241719').text('Terms & conditions', 48, notesY + 52).font('Helvetica').fontSize(8).fillColor('#5f5053').text(invoice.terms || settings.invoiceTerms || '', 48, notesY + 66, { width: 360, height: 42, ellipsis: true });
      doc.font('Helvetica').fontSize(8).fillColor('#76666a').text(settings.invoiceFooter || 'Computer-generated invoice. No physical signature is required.', 48, 718, { width: 500, align: 'center', height: 20 });
    });
  },
  async getPaymentReceiptPdf(id: string, actor: Actor) { requireBilling(actor); const payment = await billingRepository.findPayment(id); if (!payment) throw new HttpError(404, 'Payment not found'); await accessService.assertBranchAccess(actor.id, actor.role, payment.branchId); const settings = await settingsRepository.getOrCreate(); await audit(actor, { action: 'PAYMENT_RECEIPT_VIEWED', entity: 'Payment', entityId: id }); return pdfBuffer((doc) => { doc.fontSize(20).text(settings.clinicName, { align: 'center' }).fontSize(14).text('PAYMENT RECEIPT', { align: 'center' }).moveDown(); doc.fontSize(11).text(`Receipt: ${payment.paymentNo}`).text(`Patient: ${payment.patient.fullName}`).text(`Date: ${payment.paidAt.toLocaleString('en-IN')}`).text(`Mode: ${payment.mode.replaceAll('_', ' ')}`).text(`Amount: Rs ${payment.amount}`).text(`Allocated: Rs ${payment.allocatedAmount}`).text(`Advance / unallocated: Rs ${money(Number(payment.amount) - Number(payment.allocatedAmount))}`).text(`Reference: ${payment.reference ?? '-'}`).text(`Status: ${payment.status}`); }); },
};
