import type { InventoryAlertType, Prisma, PurchaseOrderStatus, Role, StockTransferStatus } from '@prisma/client';
import { Role as RoleEnum } from '@prisma/client';
import type { z } from 'zod';
import { inventoryRepository } from '../repositories/inventory.repository.js';
import { HttpError } from '../utils/http-error.js';
import type { alertActionSchema, consumableConfigSchema, consumptionConfirmSchema, goodsReceiptSchema, inventoryQuerySchema, movementReverseSchema, productSchema, productUpdateSchema, purchaseOrderActionSchema, purchaseOrderSchema, stockAdjustmentSchema, stockTransferActionSchema, stockTransferSchema, vendorSchema, vendorUpdateSchema } from '../validations/inventory.validation.js';
import { accessService } from './access.service.js';
import { auditService, type AuditContext } from './audit.service.js';
import { alertFlags, assertPurchaseOrderTransition, assertTransferTransition, quantity } from './inventory-policy.js';

type Actor = AuditContext & { id: string; role: Role };
const inventoryRoles: Role[] = [RoleEnum.ADMIN, RoleEnum.RECEPTIONIST];
const managerRoles: Role[] = [RoleEnum.ADMIN, RoleEnum.RECEPTIONIST];
const clinicalConsumptionRoles: Role[] = inventoryRoles;
function requireInventory(actor: Actor) { if (!inventoryRoles.includes(actor.role)) throw new HttpError(403, 'Inventory access is required'); }
function requireManager(actor: Actor) { if (!managerRoles.includes(actor.role)) throw new HttpError(403, 'Manager approval is required'); }
function requireConsumption(actor: Actor) { if (!clinicalConsumptionRoles.includes(actor.role)) throw new HttpError(403, 'Inventory or clinical access is required'); }
async function branch(actor: Actor, branchId?: string) { await accessService.assertBranchAccess(actor.id, actor.role, branchId); }
async function audit(actor: Actor, event: Parameters<typeof auditService.record>[1]) { const { userId, branchId, ipAddress, device, correlationId } = actor; await auditService.record({ userId, branchId, ipAddress, device, correlationId }, event); }

async function syncAlert(input: { branchId: string; productId?: string; type: InventoryAlertType; active: boolean; message: string; severity?: string; referenceType?: string; referenceId?: string; metadata?: Prisma.InputJsonValue }) {
  const existing = await inventoryRepository.findOpenAlert({ branchId: input.branchId, productId: input.productId, type: input.type, referenceId: input.referenceId });
  const { active, ...alert } = input;
  if (active && !existing) await inventoryRepository.createAlert(alert);
  if (!active && existing) await inventoryRepository.resolveAlerts(input.branchId, input.productId, input.type, input.referenceId);
}

export const inventoryService = {
  async listProducts(actor: Actor) { requireInventory(actor); return inventoryRepository.listProducts(); },
  async createProduct(input: z.infer<typeof productSchema>, actor: Actor) { requireInventory(actor); const created = await inventoryRepository.createProduct(input); await audit(actor, { action: 'PRODUCT_CREATED', entity: 'Product', entityId: created.id, newValue: { sku: created.sku, type: created.type } }); return created; },
  async updateProduct(id: string, input: z.infer<typeof productUpdateSchema>, actor: Actor) { requireInventory(actor); const existing = await inventoryRepository.findProduct(id); if (!existing) throw new HttpError(404, 'Product not found'); const updated = await inventoryRepository.updateProduct(id, input); await audit(actor, { action: 'PRODUCT_UPDATED', entity: 'Product', entityId: id }); return updated; },
  async listVendors(actor: Actor) { requireInventory(actor); return inventoryRepository.listVendors(); },
  async createVendor(input: z.infer<typeof vendorSchema>, actor: Actor) { requireInventory(actor); const created = await inventoryRepository.createVendor({ ...input, productCategories: input.productCategories }); await audit(actor, { action: 'VENDOR_CREATED', entity: 'Vendor', entityId: created.id }); return created; },
  async updateVendor(id: string, input: z.infer<typeof vendorUpdateSchema>, actor: Actor) { requireInventory(actor); const updated = await inventoryRepository.updateVendor(id, { ...input, productCategories: input.productCategories }); await audit(actor, { action: 'VENDOR_UPDATED', entity: 'Vendor', entityId: id }); return updated; },
  async listStock(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireInventory(actor); await branch(actor, query.branchId); return inventoryRepository.listStock(query.branchId, query.productId); },
  async listBatches(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireInventory(actor); await branch(actor, query.branchId); return inventoryRepository.listBatches(query.branchId, query.productId); },
  async listMovements(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireInventory(actor); await branch(actor, query.branchId); return inventoryRepository.listMovements(query.branchId, query.productId, query.take); },
  async reverseMovement(id: string, input: z.infer<typeof movementReverseSchema>, actor: Actor) { requireManager(actor); const existing = await inventoryRepository.findMovement(id); if (!existing) throw new HttpError(404, 'Stock movement not found'); await branch(actor, existing.branchId); const reversed = await inventoryRepository.reverseMovement(id, input.reason, actor.id); await audit(actor, { action: 'STOCK_MOVEMENT_REVERSED', entity: 'StockMovement', entityId: reversed.id, newValue: { reversalOfId: id, reason: input.reason } }); return reversed; },
  async listConsumableConfigs(actor: Actor) { requireConsumption(actor); return inventoryRepository.listConsumableConfigs(); },
  async saveConsumableConfig(input: z.infer<typeof consumableConfigSchema>, actor: Actor) { requireInventory(actor); const saved = await inventoryRepository.upsertConsumableConfig(input); await audit(actor, { action: 'PROCEDURE_CONSUMABLE_CONFIGURED', entity: 'ProcedureConsumableConfig', entityId: saved.id, newValue: { serviceId: input.serviceId, productId: input.productId, quantity: input.quantity } }); return saved; },

  async listPurchaseOrders(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireInventory(actor); await branch(actor, query.branchId); return inventoryRepository.listPurchaseOrders(query.branchId, query.status as PurchaseOrderStatus | undefined); },
  async createPurchaseOrder(input: z.infer<typeof purchaseOrderSchema>, actor: Actor) { requireInventory(actor); await branch(actor, input.branchId); const created = await inventoryRepository.createPurchaseOrder(input, actor.id); await audit(actor, { action: 'PURCHASE_ORDER_CREATED', entity: 'PurchaseOrder', entityId: created.id, newValue: { poNumber: created.poNumber, totalAmount: Number(created.totalAmount) } }); return created; },
  async purchaseOrderAction(id: string, input: z.infer<typeof purchaseOrderActionSchema>, actor: Actor) { requireInventory(actor); const existing = await inventoryRepository.findPurchaseOrder(id); if (!existing) throw new HttpError(404, 'Purchase order not found'); await branch(actor, existing.branchId); assertPurchaseOrderTransition(existing.status, input.status); if (input.status === 'APPROVED') requireManager(actor); if (input.status === 'CANCELLED' && ['PARTIALLY_RECEIVED', 'RECEIVED'].includes(existing.status)) throw new HttpError(409, 'Received purchase orders cannot be cancelled'); const updated = await inventoryRepository.updatePurchaseOrderStatus(id, input.status, actor.id, input.notes); await audit(actor, { action: `PURCHASE_ORDER_${input.status}`, entity: 'PurchaseOrder', entityId: id, previousValue: { status: existing.status }, newValue: { status: input.status, notes: input.notes } }); return updated; },
  async listGoodsReceipts(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireInventory(actor); await branch(actor, query.branchId); return inventoryRepository.listGoodsReceipts(query.branchId); },
  async createGoodsReceipt(input: z.infer<typeof goodsReceiptSchema>, actor: Actor) { requireInventory(actor); if (input.status !== 'POSTED') throw new HttpError(400, 'Goods receipts must be posted to update stock'); const po = await inventoryRepository.findPurchaseOrder(input.purchaseOrderId); if (!po) throw new HttpError(404, 'Purchase order not found'); await branch(actor, po.branchId); const receipt = await inventoryRepository.postGoodsReceipt(input, actor.id); await audit(actor, { action: 'GOODS_RECEIPT_POSTED', entity: 'GoodsReceipt', entityId: receipt.id, newValue: { grnNumber: receipt.grnNumber, purchaseOrderId: po.id } }); return receipt; },

  async listTransfers(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireInventory(actor); await branch(actor, query.branchId); return inventoryRepository.listTransfers(query.branchId, query.status as StockTransferStatus | undefined); },
  async createTransfer(input: z.infer<typeof stockTransferSchema>, actor: Actor) { requireInventory(actor); await Promise.all([branch(actor, input.fromBranchId), branch(actor, input.toBranchId)]); const created = await inventoryRepository.createTransfer(input, actor.id); await audit(actor, { action: 'STOCK_TRANSFER_CREATED', entity: 'StockTransfer', entityId: created.id }); return created; },
  async transferAction(id: string, input: z.infer<typeof stockTransferActionSchema>, actor: Actor) { requireInventory(actor); const existing = await inventoryRepository.findTransfer(id); if (!existing) throw new HttpError(404, 'Stock transfer not found'); await Promise.all([branch(actor, existing.fromBranchId), branch(actor, existing.toBranchId)]); assertTransferTransition(existing.status, input.status); if (input.status === 'APPROVED') requireManager(actor); const updated = await inventoryRepository.updateTransferStatus(id, input.status, actor.id, input.notes); await audit(actor, { action: `STOCK_TRANSFER_${input.status}`, entity: 'StockTransfer', entityId: id, previousValue: { status: existing.status }, newValue: { status: input.status } }); return updated; },
  async createAdjustment(input: z.infer<typeof stockAdjustmentSchema>, actor: Actor) { requireManager(actor); await branch(actor, input.branchId); if (!input.batchId) throw new HttpError(400, 'Batch is required for stock adjustments'); if (!['AVAILABLE', 'DAMAGED', 'EXPIRED'].includes(input.state)) throw new HttpError(400, 'Manual adjustments support available, damaged, or expired stock'); if (input.state !== 'AVAILABLE' && input.quantity < 0) throw new HttpError(400, 'Use a movement reversal to restore damaged or expired stock'); const adjustment = await inventoryRepository.createAdjustment(input, actor.id); await audit(actor, { action: 'STOCK_ADJUSTED', entity: 'StockAdjustment', entityId: adjustment.id, newValue: { quantity: input.quantity, reason: input.reason, state: input.state } }); return adjustment; },

  async stageProcedureConsumption(procedureSessionId: string, actor: Actor) { requireConsumption(actor); const procedure = await inventoryRepository.findProcedureForConsumption(procedureSessionId); if (!procedure) throw new HttpError(404, 'Procedure session not found'); if (procedure.status !== 'COMPLETED') return null; await branch(actor, procedure.branchId); if (procedure.inventoryConsumption) return procedure.inventoryConsumption; const serviceId = procedure.treatmentPlanItem?.serviceId ?? procedure.appointment?.serviceId; if (!serviceId) return null; const configs = await inventoryRepository.configsForService(serviceId); if (!configs.length) return null; const created = await inventoryRepository.createProcedureConsumption(procedure.id, procedure.branchId, configs); await audit(actor, { action: 'PROCEDURE_CONSUMPTION_STAGED', entity: 'ProcedureConsumption', entityId: created.id, newValue: { procedureSessionId, items: configs.length } }); if (configs.every((config) => !config.requiresConfirmation)) return this.confirmConsumption(created.id, {}, actor); return created; },
  async listConsumptions(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { requireConsumption(actor); await branch(actor, query.branchId); return inventoryRepository.listConsumptions(query.branchId, query.status as Prisma.EnumProcedureConsumptionStatusFilter | undefined); },
  async confirmConsumption(id: string, input: z.infer<typeof consumptionConfirmSchema>, actor: Actor) { requireConsumption(actor); const list = await inventoryRepository.listConsumptions(undefined); const current = list.find((item) => item.id === id); if (!current) throw new HttpError(404, 'Procedure consumption not found'); await branch(actor, current.branchId); const confirmed = await inventoryRepository.confirmConsumption(id, input.items, actor.id, input.notes); await audit(actor, { action: 'PROCEDURE_CONSUMPTION_CONFIRMED', entity: 'ProcedureConsumption', entityId: id, newValue: { procedureSessionId: confirmed.procedureSessionId } }); return confirmed; },

  async refreshAlerts(branchId: string | undefined, actor: Actor) { requireInventory(actor); await branch(actor, branchId); const [stocks, batches, purchaseOrders, transfers, recentConsumption] = await Promise.all([inventoryRepository.listStock(branchId), inventoryRepository.listBatches(branchId), inventoryRepository.listPurchaseOrders(branchId), inventoryRepository.listTransfers(branchId), inventoryRepository.recentConsumptionMovements(branchId)]);
    for (const stock of stocks) { const productBatches = batches.filter((batch) => batch.productId === stock.productId); const flags = alertFlags({ availableQuantity: stock.availableQuantity, reorderLevel: stock.product.reorderLevel }, productBatches); await syncAlert({ branchId: stock.branchId, productId: stock.productId, type: 'LOW_STOCK', active: flags.lowStock, message: `${stock.product.name} is at or below reorder level`, referenceType: 'BranchStock', referenceId: stock.id, metadata: { available: Number(stock.availableQuantity), reorderLevel: Number(stock.product.reorderLevel) } }); await syncAlert({ branchId: stock.branchId, productId: stock.productId, type: 'NEGATIVE_STOCK', active: flags.negativeStock, severity: 'CRITICAL', message: `${stock.product.name} has negative stock`, referenceType: 'BranchStock', referenceId: stock.id }); }
    for (const batch of batches) { const expired = Boolean(batch.expiryDate && batch.expiryDate <= new Date() && quantity(batch.availableQuantity) > 0); const near = Boolean(batch.expiryDate && batch.expiryDate > new Date() && batch.expiryDate <= new Date(Date.now() + 60 * 86_400_000) && quantity(batch.availableQuantity) > 0); await syncAlert({ branchId: batch.branchId, productId: batch.productId, type: 'EXPIRED_STOCK', active: expired, severity: 'CRITICAL', message: `Batch ${batch.batchNumber} of ${batch.product.name} is expired`, referenceType: 'InventoryBatch', referenceId: batch.id }); await syncAlert({ branchId: batch.branchId, productId: batch.productId, type: 'NEAR_EXPIRY', active: near, message: `Batch ${batch.batchNumber} of ${batch.product.name} expires within 60 days`, referenceType: 'InventoryBatch', referenceId: batch.id }); }
    for (const po of purchaseOrders) { const pending = ['APPROVAL_PENDING', 'APPROVED', 'ORDERED', 'PARTIALLY_RECEIVED'].includes(po.status) && Boolean(po.expectedDelivery && po.expectedDelivery < new Date()); await syncAlert({ branchId: po.branchId, type: 'PENDING_PURCHASE_ORDER', active: pending, message: `${po.poNumber} is pending beyond expected delivery`, referenceType: 'PurchaseOrder', referenceId: po.id }); }
    for (const transfer of transfers) { const pending = ['APPROVAL_PENDING', 'APPROVED', 'IN_TRANSIT'].includes(transfer.status) && transfer.requestedAt < new Date(Date.now() - 2 * 86_400_000); await syncAlert({ branchId: transfer.toBranchId, type: 'STOCK_TRANSFER_PENDING', active: pending, message: `${transfer.transferNumber} is pending`, referenceType: 'StockTransfer', referenceId: transfer.id }); }
    const grouped = new Map<string, typeof recentConsumption>(); for (const item of recentConsumption) grouped.set(item.productId, [...(grouped.get(item.productId) ?? []), item]); for (const [productId, items] of grouped) { if (items.length < 3) continue; const values = items.map((item) => Math.abs(Number(item.quantity))); const average = values.reduce((sum, value) => sum + value, 0) / values.length; const latest = items[0]; await syncAlert({ branchId: latest.branchId, productId, type: 'UNUSUAL_CONSUMPTION', active: values[0] > average * 2.5, message: `Unusual consumption detected for ${latest.product.name}`, referenceType: 'StockMovement', referenceId: latest.id, metadata: { latest: values[0], thirtyDayAverage: average } }); }
    return inventoryRepository.listAlerts(branchId); },
  async listAlerts(query: z.infer<typeof inventoryQuerySchema>, actor: Actor) { return this.refreshAlerts(query.branchId, actor); },
  async updateAlert(id: string, input: z.infer<typeof alertActionSchema>, actor: Actor) { requireInventory(actor); const alerts = await inventoryRepository.listAlerts(); const existing = alerts.find((alert) => alert.id === id); if (!existing) throw new HttpError(404, 'Inventory alert not found'); await branch(actor, existing.branchId); const updated = await inventoryRepository.updateAlert(id, input.status); await audit(actor, { action: `INVENTORY_ALERT_${input.status}`, entity: 'InventoryAlert', entityId: id }); return updated; },
};
