import type { Prisma, Role, WhatsAppAutomationTrigger, WhatsAppConsentCategory } from '@prisma/client';
import { Role as RoleEnum } from '@prisma/client';
import type { z } from 'zod';
import { env } from '../config/env.js';
import { whatsappRepository } from '../repositories/whatsapp.repository.js';
import { encryptIntegrationSecret } from '../utils/integration-crypto.js';
import { HttpError } from '../utils/http-error.js';
import type { automationSchema, broadcastActionSchema, broadcastSchema, consentSchema, conversationStartSchema, conversationUpdateSchema, internalNoteSchema, templateSchema, templateUpdateSchema, whatsappAccountSchema, whatsappMessageSchema, whatsappQuerySchema } from '../validations/whatsapp.validation.js';
import { accessService } from './access.service.js';
import { auditService, type AuditContext } from './audit.service.js';
import { normalizeWhatsAppPhone, renderWhatsAppTemplate } from './whatsapp-policy.js';
import { WhatsAppProviderError, whatsappProviderService } from './whatsapp-provider.service.js';

type Actor = AuditContext & { id: string; role: Role };
const communicationRoles: Role[] = [RoleEnum.ADMIN, RoleEnum.RECEPTIONIST];
const managerRoles: Role[] = [RoleEnum.ADMIN, RoleEnum.RECEPTIONIST];
const adminRoles: Role[] = [RoleEnum.ADMIN, RoleEnum.RECEPTIONIST];
const marketingRoles: Role[] = communicationRoles;
function requireCommunication(actor: Actor) { if (!communicationRoles.includes(actor.role)) throw new HttpError(403, 'Communication Centre access is required'); }
function requireManager(actor: Actor) { if (!managerRoles.includes(actor.role)) throw new HttpError(403, 'Manager approval is required'); }
function requireAdmin(actor: Actor) { if (!adminRoles.includes(actor.role)) throw new HttpError(403, 'Clinic administrator access is required'); }
function requireMarketing(actor: Actor) { if (!marketingRoles.includes(actor.role)) throw new HttpError(403, 'Marketing or manager access is required'); }
function requireBranchScope(actor: Actor, branchId?: string) { if (!branchId && !adminRoles.includes(actor.role)) throw new HttpError(400, 'Branch-scoped communication requests must include a branchId'); }
async function audit(actor: Actor, event: Parameters<typeof auditService.record>[1]) { const { userId, branchId, ipAddress, device, correlationId } = actor; await auditService.record({ userId, branchId, ipAddress, device, correlationId }, event); }
const secretKey = () => env.INTEGRATION_ENCRYPTION_KEY ?? `${env.JWT_ACCESS_SECRET}:${env.JWT_REFRESH_SECRET}`;
const sanitizedAccount = <T extends { accessTokenCiphertext: string; appSecretCiphertext: string; verifyTokenCiphertext: string }>(account: T) => { const { accessTokenCiphertext: _access, appSecretCiphertext: _secret, verifyTokenCiphertext: _verify, ...safe } = account; return { ...safe, credentialsConfigured: Boolean(_access && _secret && _verify) }; };

function consentCategory(input: z.infer<typeof whatsappMessageSchema>, template?: Awaited<ReturnType<typeof whatsappRepository.findTemplate>>): WhatsAppConsentCategory | undefined {
  if (input.consentCategory) return input.consentCategory;
  if (input.category === 'MARKETING') return 'MARKETING_MESSAGES';
  if (template?.group === 'APPOINTMENT') return 'APPOINTMENT_NOTIFICATIONS';
  if (template?.group === 'PAYMENT') return 'PAYMENT_REMINDERS';
  if (template && ['TREATMENT', 'CONSULTATION', 'PRESCRIPTION'].includes(template.group)) return 'TREATMENT_FOLLOW_UPS';
  if (template) return 'TRANSACTIONAL';
  return undefined;
}

async function requireConsent(phone: string, category?: WhatsAppConsentCategory) {
  if (!category) return;
  const consent = await whatsappRepository.latestConsent(phone, category);
  if (!consent?.granted || consent.withdrawnAt) throw new HttpError(409, `Active ${category.toLowerCase().replaceAll('_', ' ')} consent is required`);
}

export const whatsappService = {
  async listLogs(actor: Actor) { requireCommunication(actor); return whatsappRepository.listLegacyLogs(); },
  async listAccounts(actor: Actor) { requireAdmin(actor); return (await whatsappRepository.listAccounts()).map(sanitizedAccount); },
  async setupAccount(input: z.infer<typeof whatsappAccountSchema>, actor: Actor) { requireAdmin(actor); if (env.NODE_ENV === 'production' && !env.INTEGRATION_ENCRYPTION_KEY) throw new HttpError(503, 'INTEGRATION_ENCRYPTION_KEY must be configured before connecting WhatsApp in production'); for (const phone of input.phoneNumbers) await accessService.assertBranchAccess(actor.id, actor.role, phone.branchId); const account = await whatsappRepository.upsertAccount(input.businessAccountId, { name: input.name, businessAccountId: input.businessAccountId, appId: input.appId, accessTokenCiphertext: encryptIntegrationSecret(input.accessToken, secretKey()), appSecretCiphertext: encryptIntegrationSecret(input.appSecret, secretKey()), verifyTokenCiphertext: encryptIntegrationSecret(input.verifyToken, secretKey()), apiVersion: input.apiVersion, tokenExpiresAt: input.tokenExpiresAt, status: 'DISCONNECTED' }); for (const phone of input.phoneNumbers) await whatsappRepository.upsertPhoneNumber(phone.phoneNumberId, { accountId: account.id, branchId: phone.branchId, phoneNumberId: phone.phoneNumberId, displayPhoneNumber: phone.displayPhoneNumber, normalizedPhone: normalizeWhatsAppPhone(phone.displayPhoneNumber), verifiedName: phone.verifiedName, qualityRating: phone.qualityRating, messagingLimit: phone.messagingLimit, isDefault: phone.isDefault, active: true }); try { await whatsappProviderService.testConnection(account); const connected = await whatsappRepository.updateAccount(account.id, { status: 'CONNECTED', lastSyncAt: new Date(), lastFailureAt: null, lastFailureReason: null }); await audit(actor, { action: 'WHATSAPP_ACCOUNT_CONNECTED', entity: 'WhatsAppAccount', entityId: account.id, newValue: { businessAccountId: account.businessAccountId, phoneNumbers: input.phoneNumbers.length } }); return sanitizedAccount({ ...connected, phoneNumbers: (await whatsappRepository.listPhoneNumbers()).filter((phone) => phone.accountId === account.id) }); } catch (error) { const reason = error instanceof Error ? error.message : 'Connection failed'; await whatsappRepository.updateAccount(account.id, { status: 'ERROR', lastFailureAt: new Date(), lastFailureReason: reason }); throw new HttpError(502, `WhatsApp connection failed: ${reason}`); } },
  async testAccount(id: string, actor: Actor) { requireAdmin(actor); const account = await whatsappRepository.findAccount(id); if (!account) throw new HttpError(404, 'WhatsApp account not found'); try { const response = await whatsappProviderService.testConnection(account); await whatsappRepository.updateAccount(id, { status: 'CONNECTED', lastSyncAt: new Date(), lastFailureReason: null }); await audit(actor, { action: 'WHATSAPP_CONNECTION_TESTED', entity: 'WhatsAppAccount', entityId: id }); return { connected: true, response }; } catch (error) { const reason = error instanceof Error ? error.message : 'Connection failed'; await whatsappRepository.updateAccount(id, { status: 'ERROR', lastFailureAt: new Date(), lastFailureReason: reason }); throw new HttpError(502, reason); } },
  async disconnectAccount(id: string, actor: Actor) { requireAdmin(actor); const updated = await whatsappRepository.updateAccount(id, { status: 'DISCONNECTED' }); await audit(actor, { action: 'WHATSAPP_ACCOUNT_DISCONNECTED', entity: 'WhatsAppAccount', entityId: id }); return sanitizedAccount(updated); },
  async listPhoneNumbers(branchId: string | undefined, actor: Actor) { requireCommunication(actor); requireBranchScope(actor, branchId); await accessService.assertBranchAccess(actor.id, actor.role, branchId); return whatsappRepository.listPhoneNumbers(branchId); },

  async listTemplates(query: z.infer<typeof whatsappQuerySchema>, actor: Actor) { requireCommunication(actor); requireBranchScope(actor, query.branchId); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return whatsappRepository.listTemplates({ branchId: query.branchId, accountId: query.accountId, status: query.status as Prisma.EnumWhatsAppTemplateStatusFilter['equals'] }); },
  async createTemplate(input: z.infer<typeof templateSchema>, actor: Actor) { requireAdmin(actor); await accessService.assertBranchAccess(actor.id, actor.role, input.branchId); const created = await whatsappRepository.createTemplate({ ...input, status: 'DRAFT', active: false, buttons: input.buttons as Prisma.InputJsonValue, variables: input.variables as Prisma.InputJsonValue, createdById: actor.id }); await audit(actor, { action: 'WHATSAPP_TEMPLATE_CREATED', entity: 'WhatsAppTemplate', entityId: created.id, newValue: { name: created.name, language: created.language } }); return created; },
  async updateTemplate(id: string, input: z.infer<typeof templateUpdateSchema>, actor: Actor) { requireAdmin(actor); const existing = await whatsappRepository.findTemplate(id); if (!existing) throw new HttpError(404, 'Template not found'); await accessService.assertBranchAccess(actor.id, actor.role, existing.branchId ?? undefined); const editable = { ...input }; delete editable.status; const requestedActive = editable.active; const updated = await whatsappRepository.updateTemplate(id, { ...editable, active: existing.status === 'APPROVED' ? requestedActive : false, buttons: input.buttons as Prisma.InputJsonValue | undefined, variables: input.variables as Prisma.InputJsonValue | undefined }); await audit(actor, { action: 'WHATSAPP_TEMPLATE_UPDATED', entity: 'WhatsAppTemplate', entityId: id }); return updated; },
  async syncTemplates(accountId: string, actor: Actor) { requireAdmin(actor); const account = await whatsappRepository.findAccount(accountId); if (!account) throw new HttpError(404, 'Account not found'); const response = await whatsappProviderService.syncTemplates(account); const mapped = []; for (const item of response.data) { const body = item.components?.find((part) => part.type === 'BODY')?.text ?? ''; const buttons = item.components?.find((part) => part.type === 'BUTTONS')?.buttons; const status = ['APPROVED', 'REJECTED', 'PAUSED', 'DISABLED'].includes(item.status) ? item.status as 'APPROVED' | 'REJECTED' | 'PAUSED' | 'DISABLED' : 'SUBMITTED'; const category = ['AUTHENTICATION', 'MARKETING', 'UTILITY'].includes(item.category) ? item.category as 'AUTHENTICATION' | 'MARKETING' | 'UTILITY' : 'UTILITY'; mapped.push(await whatsappRepository.upsertProviderTemplate({ accountId, providerTemplateId: item.id, name: item.name, displayName: item.name.replaceAll('_', ' '), language: item.language, category, status, body, buttons: buttons as Prisma.InputJsonValue | undefined, rejectionReason: item.rejected_reason })); } await whatsappRepository.updateAccount(accountId, { lastSyncAt: new Date(), status: 'CONNECTED' }); await audit(actor, { action: 'WHATSAPP_TEMPLATES_SYNCED', entity: 'WhatsAppAccount', entityId: accountId, newValue: { count: mapped.length } }); return mapped; },

  async listConversations(query: z.infer<typeof whatsappQuerySchema>, actor: Actor) { requireCommunication(actor); requireBranchScope(actor, query.branchId); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return whatsappRepository.listConversations({ branchId: query.branchId, status: query.status as Prisma.EnumWhatsAppConversationStatusFilter['equals'], assignedToId: query.mine ? actor.id : query.assignedToId, unassigned: query.unassigned, unread: query.unread, search: query.search, failed: query.failed }); },
  async getConversation(id: string, actor: Actor) { requireCommunication(actor); const conversation = await whatsappRepository.findConversation(id); if (!conversation) throw new HttpError(404, 'Conversation not found'); await accessService.assertBranchAccess(actor.id, actor.role, conversation.branchId); await whatsappRepository.markConversationRead(id); return { ...conversation, unreadCount: 0 }; },
  async startConversation(input: z.infer<typeof conversationStartSchema>, actor: Actor) { requireCommunication(actor); const phone = await whatsappRepository.findPhoneNumber(input.phoneNumberId); if (!phone?.active || phone.account.status !== 'CONNECTED') throw new HttpError(409, 'An active connected WhatsApp phone number is required'); await accessService.assertBranchAccess(actor.id, actor.role, phone.branchId); const normalizedMobile = normalizeWhatsAppPhone(input.mobile); const existing = await whatsappRepository.findConversationByPhone(phone.id, normalizedMobile); if (existing) return existing; const contact = await whatsappRepository.findContact(normalizedMobile); const created = await whatsappRepository.createConversation({ phoneNumberId: phone.id, normalizedMobile, contactName: input.contactName ?? contact?.fullName, personId: input.personId ?? contact?.id, leadId: input.leadId ?? contact?.leads[0]?.id, patientId: input.patientId ?? contact?.patient?.id, appointmentId: input.appointmentId, invoiceId: input.invoiceId, packageId: input.packageId, branchId: phone.branchId, assignedToId: actor.id, status: 'OPEN' }); await audit(actor, { action: 'WHATSAPP_CONVERSATION_STARTED', entity: 'WhatsAppConversation', entityId: created.id }); return created; },
  async updateConversation(id: string, input: z.infer<typeof conversationUpdateSchema>, actor: Actor) { requireCommunication(actor); const existing = await whatsappRepository.findConversation(id); if (!existing) throw new HttpError(404, 'Conversation not found'); await accessService.assertBranchAccess(actor.id, actor.role, existing.branchId); const updated = await whatsappRepository.updateConversation(id, { ...input, resolvedAt: input.status === 'RESOLVED' ? new Date() : undefined, closedAt: input.status === 'CLOSED' ? new Date() : undefined }); await audit(actor, { action: 'WHATSAPP_CONVERSATION_UPDATED', entity: 'WhatsAppConversation', entityId: id, newValue: input as Prisma.InputJsonValue }); return updated; },
  async addInternalNote(id: string, input: z.infer<typeof internalNoteSchema>, actor: Actor) { requireCommunication(actor); const conversation = await whatsappRepository.findConversation(id); if (!conversation) throw new HttpError(404, 'Conversation not found'); await accessService.assertBranchAccess(actor.id, actor.role, conversation.branchId); const message = await whatsappRepository.createInternalNote({ conversationId: id, phoneNumberId: conversation.phoneNumberId, direction: 'INTERNAL', type: 'INTERNAL_NOTE', status: 'RECEIVED', sender: actor.id, recipient: 'clinic-team', content: input.content, createdById: actor.id }); await audit(actor, { action: 'WHATSAPP_INTERNAL_NOTE_ADDED', entity: 'WhatsAppConversation', entityId: id }); return message; },
  async queueMessage(input: z.infer<typeof whatsappMessageSchema>, actor: Actor) { requireCommunication(actor); const conversation = await whatsappRepository.findConversation(input.conversationId); if (!conversation) throw new HttpError(404, 'Conversation not found'); await accessService.assertBranchAccess(actor.id, actor.role, conversation.branchId); const phone = await whatsappRepository.findPhoneNumber(conversation.phoneNumberId); if (!phone || phone.account.status !== 'CONNECTED') throw new HttpError(409, 'WhatsApp account is not connected'); const template = input.templateId ? await whatsappRepository.findTemplate(input.templateId) : null; if (input.templateId && (!template || template.status !== 'APPROVED' || !template.active)) throw new HttpError(409, 'An active approved template is required'); if (!template && (!conversation.sessionExpiresAt || conversation.sessionExpiresAt < new Date())) throw new HttpError(409, 'The 24-hour service window is closed; use an approved template'); const category = consentCategory(input, template); await requireConsent(conversation.normalizedMobile, category); const scheduledAt = input.scheduledAt ?? new Date(); const message = await whatsappRepository.createOutboundMessage({ conversationId: conversation.id, phoneNumberId: phone.id, direction: 'OUTBOUND', type: template ? 'TEMPLATE' : input.type, status: scheduledAt > new Date() ? 'SCHEDULED' : 'QUEUED', sender: phone.normalizedPhone, recipient: conversation.normalizedMobile, content: template ? renderWhatsAppTemplate(template.body, input.variables) : input.content, mediaId: input.mediaId, mediaUrl: input.mediaUrl, mimeType: input.mimeType, filename: input.filename, templateId: template?.id, templateName: template?.name, templateLanguage: template?.language, category: input.category, relatedRecordType: input.relatedRecordType, relatedRecordId: input.relatedRecordId, scheduledAt, interactivePayload: template ? input.variables : input.interactivePayload as Prisma.InputJsonValue, createdById: actor.id }); await whatsappRepository.createJob({ type: 'WHATSAPP_SEND', idempotencyKey: `wa-send:${message.id}`, branchId: conversation.branchId, payload: { messageId: message.id, referenceType: input.relatedRecordType, referenceId: input.relatedRecordId }, runAt: scheduledAt }); await audit(actor, { action: 'WHATSAPP_MESSAGE_QUEUED', entity: 'WhatsAppMessage', entityId: message.id, newValue: { templateId: template?.id, scheduledAt } }); return message; },

  async recordConsent(input: z.infer<typeof consentSchema>, actor: Actor) { requireCommunication(actor); const normalizedPhone = normalizeWhatsAppPhone(input.phoneNumber); const consent = await whatsappRepository.recordConsent({ ...input, normalizedPhone, consentedAt: input.consentedAt, withdrawnAt: input.granted ? undefined : new Date(), withdrawalReason: input.granted ? undefined : input.withdrawalReason ?? 'Consent withdrawn' }); await audit(actor, { action: input.granted ? 'WHATSAPP_CONSENT_GRANTED' : 'WHATSAPP_CONSENT_WITHDRAWN', entity: 'WhatsAppOptIn', entityId: consent.id, newValue: { category: input.category, normalizedPhone } }); return consent; },
  async listConsents(phone: string | undefined, actor: Actor) { requireCommunication(actor); return whatsappRepository.consentHistory(phone ? normalizeWhatsAppPhone(phone) : undefined); },

  async listAutomations(branchId: string | undefined, actor: Actor) { requireCommunication(actor); requireBranchScope(actor, branchId); await accessService.assertBranchAccess(actor.id, actor.role, branchId); return whatsappRepository.listAutomations(branchId); },
  async saveAutomation(input: z.infer<typeof automationSchema>, actor: Actor) { requireAdmin(actor); await accessService.assertBranchAccess(actor.id, actor.role, input.branchId); const template = await whatsappRepository.findTemplate(input.templateId); if (!template) throw new HttpError(404, 'Template not found'); if (input.active && (template.status !== 'APPROVED' || !template.active)) throw new HttpError(409, 'Only an active provider-approved template can activate an automation'); const saved = await whatsappRepository.upsertAutomation({ ...input, stopConditions: input.stopConditions }); await audit(actor, { action: 'WHATSAPP_AUTOMATION_SAVED', entity: 'WhatsAppAutomation', entityId: saved.id }); return saved; },
  async scheduleReferenceAutomations(trigger: WhatsAppAutomationTrigger, referenceType: 'Appointment' | 'Lead', referenceId: string, branchId: string, baseTime = new Date()) { const automations = await whatsappRepository.findAutomations(trigger, branchId); const jobs = []; for (const automation of automations) { let runAt = new Date(baseTime.getTime() + automation.delayMinutes * 60_000); if (automation.trigger === 'APPOINTMENT_TOMORROW') runAt = new Date(baseTime.getTime() - 24 * 60 * 60_000 + automation.delayMinutes * 60_000); if (automation.trigger === 'APPOINTMENT_IN_ONE_HOUR') runAt = new Date(baseTime.getTime() - 60 * 60_000 + automation.delayMinutes * 60_000); if (runAt < new Date()) runAt = new Date(); jobs.push(await whatsappRepository.createJob({ type: referenceType === 'Appointment' ? 'WHATSAPP_APPOINTMENT_AUTOMATION' : 'WHATSAPP_LEAD_AUTOMATION', idempotencyKey: `wa-auto:${automation.id}:${referenceType}:${referenceId}:${baseTime.toISOString()}`, branchId, payload: { automationId: automation.id, referenceType, referenceId }, runAt })); } return jobs; },
  async rescheduleAppointmentAutomations(referenceId: string, branchId: string, appointmentAt: Date, event: 'BOOKED' | 'RESCHEDULED' | 'CANCELLED' | 'MISSED' = 'BOOKED') {
    await whatsappRepository.cancelJobs('Appointment', referenceId);
    const immediateTrigger = event === 'BOOKED' ? 'APPOINTMENT_BOOKED' : event === 'RESCHEDULED' ? 'APPOINTMENT_RESCHEDULED' : event === 'CANCELLED' ? 'APPOINTMENT_CANCELLED' : 'APPOINTMENT_MISSED';
    const jobs = await this.scheduleReferenceAutomations(immediateTrigger, 'Appointment', referenceId, branchId, new Date());
    if (event === 'BOOKED' || event === 'RESCHEDULED') {
      jobs.push(...await this.scheduleReferenceAutomations('APPOINTMENT_CONFIRMATION', 'Appointment', referenceId, branchId, new Date()));
      jobs.push(...await this.scheduleReferenceAutomations('APPOINTMENT_TOMORROW', 'Appointment', referenceId, branchId, appointmentAt));
      jobs.push(...await this.scheduleReferenceAutomations('APPOINTMENT_IN_ONE_HOUR', 'Appointment', referenceId, branchId, appointmentAt));
    }
    return jobs;
  },

  async listBroadcasts(query: z.infer<typeof whatsappQuerySchema>, actor: Actor) { requireMarketing(actor); requireBranchScope(actor, query.branchId); await accessService.assertBranchAccess(actor.id, actor.role, query.branchId); return whatsappRepository.listBroadcasts(query.branchId, query.status as Prisma.EnumWhatsAppBroadcastStatusFilter['equals']); },
  async createBroadcast(input: z.infer<typeof broadcastSchema>, actor: Actor) { requireMarketing(actor); requireBranchScope(actor, input.branchId); await accessService.assertBranchAccess(actor.id, actor.role, input.branchId); const template = await whatsappRepository.findTemplate(input.templateId); const phone = await whatsappRepository.findPhoneNumber(input.phoneNumberId); if (!template || template.status !== 'APPROVED' || !template.active || template.category !== 'MARKETING') throw new HttpError(409, 'Broadcasts require an active provider-approved marketing template'); if (!phone || phone.accountId !== input.accountId) throw new HttpError(400, 'Phone number does not belong to the selected account'); if (input.branchId && phone.branchId !== input.branchId) throw new HttpError(400, 'Phone number is not mapped to the selected branch'); if (template.accountId && template.accountId !== input.accountId) throw new HttpError(400, 'Template does not belong to the selected account'); const broadcast = await whatsappRepository.createBroadcast({ ...input, segmentation: input.segmentation as Prisma.InputJsonValue, variableDefaults: input.variableDefaults, createdById: actor.id }); const candidates = await whatsappRepository.buildBroadcastRecipients(broadcast.id, input.segmentation); let filtered = 0; for (const recipient of candidates) { const consent = await whatsappRepository.latestConsent(recipient.normalizedPhone, 'PROMOTIONAL_BROADCASTS'); if (!consent?.granted || consent.withdrawnAt) { await whatsappRepository.updateRecipient(recipient.id, { status: 'OPTED_OUT', filterReason: 'Promotional broadcast consent is not active' }); filtered += 1; } } const updated = await whatsappRepository.updateBroadcast(broadcast.id, { filteredCount: filtered }); await audit(actor, { action: 'WHATSAPP_BROADCAST_CREATED', entity: 'WhatsAppBroadcast', entityId: broadcast.id, newValue: { recipientCount: candidates.length, filtered } }); return updated; },
  async broadcastAction(id: string, input: z.infer<typeof broadcastActionSchema>, actor: Actor) { requireMarketing(actor); const broadcast = await whatsappRepository.findBroadcast(id); if (!broadcast) throw new HttpError(404, 'Broadcast not found'); await accessService.assertBranchAccess(actor.id, actor.role, broadcast.branchId ?? undefined); const allowed: Record<string, string[]> = { DRAFT: ['APPROVAL_PENDING', 'CANCELLED'], APPROVAL_PENDING: ['APPROVED', 'CANCELLED'], APPROVED: ['SCHEDULED', 'CANCELLED'], SCHEDULED: ['CANCELLED'], SENDING: ['CANCELLED'] }; if (!allowed[broadcast.status]?.includes(input.status)) throw new HttpError(409, `Broadcast cannot move from ${broadcast.status} to ${input.status}`); if (input.status === 'APPROVED') requireManager(actor); const scheduledAt = broadcast.scheduledAt ?? new Date(); const updated = await whatsappRepository.updateBroadcast(id, { status: input.status, approvalNotes: input.notes, ...(input.status === 'APPROVED' ? { approvedById: actor.id, approvedAt: new Date() } : {}), ...(input.status === 'SCHEDULED' ? { scheduledAt } : {}), ...(input.status === 'CANCELLED' ? { cancelledAt: new Date() } : {}) }); if (input.status === 'SCHEDULED') await whatsappRepository.createJob({ type: 'WHATSAPP_BROADCAST', idempotencyKey: `wa-broadcast:${id}`, branchId: broadcast.branchId, payload: { broadcastId: id }, runAt: scheduledAt }); if (input.status === 'CANCELLED') await whatsappRepository.cancelJobs('WhatsAppBroadcast', id); await audit(actor, { action: `WHATSAPP_BROADCAST_${input.status}`, entity: 'WhatsAppBroadcast', entityId: id }); return updated; },
  async listWebhookEvents(accountId: string | undefined, actor: Actor) { requireAdmin(actor); return whatsappRepository.listWebhookEvents(accountId); },
  async listJobs(status: Prisma.EnumDurableJobStatusFilter['equals'] | undefined, actor: Actor) { requireAdmin(actor); return whatsappRepository.listJobs(status); },
  async listFailures(accountId: string | undefined, actor: Actor) { requireAdmin(actor); return whatsappRepository.listFailureLogs(accountId); },
  providerError(error: unknown) { return error instanceof WhatsAppProviderError ? error : new WhatsAppProviderError(error instanceof Error ? error.message : 'Unknown provider error', 'UNKNOWN', true); },
};
