'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, CalendarDays, ClipboardPlus, FileLock2, Pill, Plus, Stethoscope } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { apiBlob, apiRequest } from '@/services/api';
import { useSessionStore } from '@/store/session-store';
import type { ClinicResource } from '@/types/appointment';
import type { Patient360 } from '@/types/clinical';
import type { StaffMember } from '@/types/front-desk';
import { PatientDocumentsPanel, PatientFormsPanel, PatientGalleryPanel } from './patient-forms-files-panel';

const tabs = ['Overview', 'Timeline', 'Medical Profile', 'Appointments', 'Clinical Encounters', 'Treatment Plans', 'Procedure Sessions', 'Prescriptions', 'Forms & Consents', 'Photo Gallery', 'Documents'] as const;
type Tab = typeof tabs[number];
const clinicalRoles = ['ADMIN', 'RECEPTIONIST'];
const prescriberRoles = ['ADMIN', 'RECEPTIONIST'];
const format = (value?: string | null) => value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
const nowLocal = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };

export function Patient360View({ patientId }: { patientId: string }) {
  const queryClient = useQueryClient();
  const { session } = useSessionStore();
  const [tab, setTab] = useState<Tab>('Overview');
  const [composer, setComposer] = useState<'encounter' | 'plan' | 'procedure' | 'prescription' | null>(null);
  const patientQuery = useQuery({ queryKey: ['patient-360', patientId], queryFn: () => apiRequest<{ data: Patient360 }>(`/clinical/patients/${patientId}/360`) });
  const patient = patientQuery.data?.data;
  const canClinical = Boolean(session && clinicalRoles.includes(session.user.role));
  const canPrescribe = Boolean(session && prescriberRoles.includes(session.user.role));
  const staffQuery = useQuery({ queryKey: ['clinical-staff', patient?.branchId], queryFn: () => apiRequest<{ data: StaffMember[] }>(`/front-desk/staff?branchId=${patient?.branchId}`), enabled: Boolean(patient?.branchId && canClinical) });
  const resourcesQuery = useQuery({ queryKey: ['clinical-resources', patient?.branchId], queryFn: () => apiRequest<{ data: ClinicResource[] }>(`/front-desk/resources?branchId=${patient?.branchId}`), enabled: Boolean(patient?.branchId && canClinical) });
  const staff = staffQuery.data?.data ?? [];
  const doctors = staff.filter((member) => member.role === 'ADMIN');
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ['patient-360', patientId] });

  if (patientQuery.isLoading) return <Card className="text-sm text-muted-foreground">Loading the complete patient journey…</Card>;
  if (patientQuery.isError || !patient) return <Card className="border-red-200 text-sm text-red-700">{patientQuery.error?.message ?? 'Patient record could not be loaded.'}</Card>;

  const allergy = patient.medicalProfile?.allergyToDrugs || patient.medicalProfile?.productAllergies || patient.medicalProfile?.foodAllergies;
  return <section className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div><Link href="/patients" className="mb-2 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Patient directory</Link><h1 className="text-2xl font-semibold">{patient.fullName}</h1><p className="text-sm text-muted-foreground">{patient.patientNo} · {patient.mobile} · {patient.branch?.name}</p></div>
      {canClinical ? <div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={() => setComposer('encounter')}><ClipboardPlus className="size-4" />New encounter</Button><Button type="button" onClick={() => setComposer('prescription')} disabled={!canPrescribe}><Pill className="size-4" />Prescription</Button></div> : null}
    </div>

    {patient.medicalProfile?.criticalAlert ? <Card className="border-red-300 bg-red-50 text-red-900"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0" /><div><div className="font-semibold">Critical medical alert</div><div className="text-sm">{patient.medicalProfile.clinicalAlerts || allergy || 'Review the medical profile before treatment.'}</div></div></div></Card> : null}

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Metric title="Assigned doctor" value={patient.assignedDoctor?.name ?? 'Not assigned'} />
      <Metric title="Allergies" value={allergy ?? 'None recorded'} warning={Boolean(allergy)} />
      <Metric title="Last visit" value={format(patient.summary.lastVisit?.appointmentAt)} />
      <Metric title="Next appointment" value={format(patient.summary.nextAppointment?.appointmentAt)} />
      <Metric title="Sessions remaining" value={String(patient.summary.sessionsRemaining)} />
    </div>

    <div className="overflow-x-auto border-b"><div className="flex min-w-max gap-1">{tabs.map((item) => <button key={item} className={`border-b-2 px-3 py-2 text-sm ${tab === item ? 'border-primary font-medium text-primary' : 'border-transparent text-muted-foreground'}`} onClick={() => setTab(item)}>{item}</button>)}</div></div>

    {tab === 'Overview' ? <Overview patient={patient} onCompose={setComposer} canClinical={canClinical} canPrescribe={canPrescribe} /> : null}
    {tab === 'Timeline' ? <ListState empty="No journey events have been recorded." items={patient.timelineEvents.map((event) => <Record key={event.id} title={event.title} subtitle={`${format(event.createdAt)}${event.description ? ` · ${event.description}` : ''}`} />)} /> : null}
    {tab === 'Medical Profile' ? <MedicalProfile patient={patient} canEdit={canClinical} invalidate={invalidate} /> : null}
    {tab === 'Appointments' ? <ListState empty="No appointments recorded." items={patient.lead.appointments.map((appointment) => <Record key={appointment.id} title={`${label(appointment.status)} · ${appointment.service?.name ?? label(appointment.appointmentType)}`} subtitle={`${format(appointment.appointmentAt)} · ${appointment.doctor?.name ?? 'Practitioner not assigned'}`} />)} /> : null}
    {tab === 'Clinical Encounters' ? <Encounters patient={patient} canSign={canPrescribe} invalidate={invalidate} /> : null}
    {tab === 'Treatment Plans' ? <ListState empty="No treatment plans created." action={canClinical ? <Button onClick={() => setComposer('plan')}><Plus className="size-4" />New plan</Button> : undefined} items={(patient.treatmentPlans ?? []).map((plan) => <Record key={plan.id} title={`${plan.concern} · ${label(plan.status)}`} subtitle={`${plan.assignedDoctor.name} · ${plan.items.map((item) => `${item.name} ${item.completedSessions}/${item.plannedSessions}`).join(', ')}`} />)} /> : null}
    {tab === 'Procedure Sessions' ? <ListState empty="No structured procedure sessions recorded." action={canClinical ? <Button onClick={() => setComposer('procedure')}><Plus className="size-4" />Record procedure</Button> : undefined} items={(patient.procedureSessions ?? []).map((procedure) => <Record key={procedure.id} title={`${procedure.procedureName} · ${label(procedure.status)}`} subtitle={`${format(procedure.performedAt ?? procedure.createdAt)} · ${procedure.practitioner.name}${procedure.adverseEventFlag ? ' · Adverse-event alert' : ''}`} warning={procedure.adverseEventFlag} />)} /> : null}
    {tab === 'Prescriptions' ? <Prescriptions patient={patient} canSign={canPrescribe} onCreate={() => setComposer('prescription')} invalidate={invalidate} /> : null}
    {tab === 'Forms & Consents' ? <PatientFormsPanel patient={patient} /> : null}
    {tab === 'Photo Gallery' ? <PatientGalleryPanel patient={patient} /> : null}
    {tab === 'Documents' ? <PatientDocumentsPanel patient={patient} /> : null}

    {composer ? <ClinicalComposer kind={composer} patient={patient} staff={staff} resources={resourcesQuery.data?.data ?? []} defaultDoctorId={session?.user.role === 'DOCTOR' ? session.user.id : doctors[0]?.id} onClose={() => setComposer(null)} onSaved={() => { setComposer(null); invalidate(); }} /> : null}
  </section>;
}

function Metric({ title, value, warning }: { title: string; value: string; warning?: boolean }) { return <Card className="p-4"><div className="text-xs text-muted-foreground">{title}</div><div className={`mt-1 text-sm font-semibold ${warning ? 'text-red-700' : ''}`}>{value}</div></Card>; }
function Record({ title, subtitle, warning }: { title: string; subtitle: string; warning?: boolean }) { return <div className={`rounded-md border p-3 ${warning ? 'border-red-200 bg-red-50' : ''}`}><div className="font-medium">{title}</div><div className="mt-1 text-xs text-muted-foreground">{subtitle}</div></div>; }
function ListState({ items, empty, action }: { items: React.ReactNode[]; empty: string; action?: React.ReactNode }) { return <Card><div className="mb-3 flex justify-end">{action}</div>{items.length ? <div className="space-y-2">{items}</div> : <div className="py-8 text-center text-sm text-muted-foreground">{empty}</div>}</Card>; }

function Overview({ patient, onCompose, canClinical, canPrescribe }: { patient: Patient360; onCompose: (value: 'encounter' | 'plan' | 'procedure' | 'prescription') => void; canClinical: boolean; canPrescribe: boolean }) {
  return <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><h2 className="font-semibold">Current clinical picture</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Detail title="Primary concern" value={patient.primaryConcern ?? patient.medicalProfile?.skinConcern ?? patient.medicalProfile?.hairConcern} /><Detail title="Active treatment plan" value={patient.summary.activeTreatmentPlan?.concern} /><Detail title="Medical history" value={patient.medicalProfile?.medicalHistory} /><Detail title="Current medicines" value={patient.medicalProfile?.currentMedications} /><Detail title="Clinical alerts" value={patient.medicalProfile?.clinicalAlerts} /><Detail title="Communication consent" value={patient.person?.transactionalConsent ? 'Transactional communication allowed' : 'Not recorded'} /></dl></Card><Card><h2 className="font-semibold">Quick actions</h2><div className="mt-4 grid gap-2">{canClinical ? <><Button variant="secondary" onClick={() => onCompose('encounter')}><Stethoscope className="size-4" />Start consultation</Button><Button variant="secondary" onClick={() => onCompose('plan')}><ClipboardPlus className="size-4" />Create treatment plan</Button><Button variant="secondary" onClick={() => onCompose('procedure')}><CalendarDays className="size-4" />Record procedure</Button></> : null}{canPrescribe ? <Button variant="secondary" onClick={() => onCompose('prescription')}><Pill className="size-4" />Add prescription</Button> : null}<Link href={`/appointments?patient=${patient.id}`} className="inline-flex h-10 items-center justify-center rounded-md border px-4 text-sm font-medium">Request appointment</Link></div></Card></div>;
}
function Detail({ title, value }: { title: string; value?: string | null }) { return <div><dt className="text-xs font-medium text-muted-foreground">{title}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{value || 'Not recorded'}</dd></div>; }
function MedicalProfile({ patient, canEdit, invalidate }: { patient: Patient360; canEdit: boolean; invalidate: () => void }) {
  const profile = patient.medicalProfile; const [editing, setEditing] = useState(false);
  const [values, setValues] = useState({ medicalHistory: profile?.medicalHistory ?? '', currentMedications: profile?.currentMedications ?? '', allergyToDrugs: profile?.allergyToDrugs ?? '', clinicalAlerts: profile?.clinicalAlerts ?? '', criticalAlert: Boolean(profile?.criticalAlert), reasonForChange: '' });
  const mutation = useMutation({ mutationFn: () => apiRequest(`/patients/${patient.id}/medical-profile`, { method: 'PUT', body: JSON.stringify(values) }), onSuccess: () => { setEditing(false); invalidate(); } });
  if (!profile) return <Card className="text-sm text-muted-foreground">Medical profile is unavailable for your role or has not been recorded.</Card>;
  const fields = [['Skin concern', profile.skinConcern], ['Hair concern', profile.hairConcern], ['Medical history', profile.medicalHistory], ['Surgical history', profile.surgicalHistory], ['Current medicines', profile.currentMedications], ['Drug allergies', profile.allergyToDrugs], ['Product allergies', profile.productAllergies], ['Food allergies', profile.foodAllergies], ['Family history', profile.familyHistory], ['Smoking', profile.smokingStatus], ['Alcohol', profile.alcoholHistory], ['Clinical alerts', profile.clinicalAlerts]];
  return <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><div className="mb-4 flex justify-between"><h2 className="font-semibold">Current medical profile</h2>{canEdit ? <Button variant="secondary" onClick={() => setEditing((value) => !value)}>{editing ? 'Cancel edit' : 'Update profile'}</Button> : null}</div>{editing ? <div className="grid gap-3 sm:grid-cols-2"><Area label="Medical history" name="medicalHistory" values={values} set={(name, value) => setValues((current) => ({ ...current, [name]: value }))} /><Area label="Current medications" name="currentMedications" values={values} set={(name, value) => setValues((current) => ({ ...current, [name]: value }))} /><Area label="Drug allergies" name="allergyToDrugs" values={values} set={(name, value) => setValues((current) => ({ ...current, [name]: value }))} /><Area label="Clinical alerts" name="clinicalAlerts" values={values} set={(name, value) => setValues((current) => ({ ...current, [name]: value }))} /><TextField label="Reason for change" name="reasonForChange" values={values} set={(name, value) => setValues((current) => ({ ...current, [name]: value }))} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={values.criticalAlert} onChange={(event) => setValues((current) => ({ ...current, criticalAlert: event.target.checked }))} />Critical alert</label>{mutation.isError ? <p className="text-sm text-red-700 sm:col-span-2">{mutation.error.message}</p> : null}<Button className="sm:col-span-2" disabled={mutation.isPending} onClick={() => mutation.mutate()}>Save versioned update</Button></div> : <div className="grid gap-4 sm:grid-cols-2">{fields.map(([title, value]) => <Detail key={title} title={title ?? ''} value={value as string | null} />)}</div>}</Card><Card><h2 className="font-semibold">Version history</h2><div className="mt-3 space-y-2">{profile.versions?.length ? profile.versions.map((version) => <Record key={version.id} title={version.reason || 'Medical profile updated'} subtitle={`${format(version.createdAt)} · ${version.updatedBy?.name ?? 'System'}`} />) : <p className="text-sm text-muted-foreground">No previous versions.</p>}</div></Card></div>;
}

function Encounters({ patient, canSign, invalidate }: { patient: Patient360; canSign: boolean; invalidate: () => void }) {
  const sign = useMutation({ mutationFn: (id: string) => apiRequest(`/clinical/encounters/${id}/sign`, { method: 'POST', body: '{}' }), onSuccess: invalidate });
  const addendum = useMutation({ mutationFn: ({ id, content }: { id: string; content: string }) => apiRequest(`/clinical/encounters/${id}/addendums`, { method: 'POST', body: JSON.stringify({ content }) }), onSuccess: invalidate });
  const entries = patient.clinicalEncounters ?? [];
  return <ListState empty="No clinical encounters recorded." items={entries.map((encounter) => <Card key={encounter.id} className="p-4"><div className="flex flex-wrap justify-between gap-2"><div><div className="font-semibold">{label(encounter.type)} · {label(encounter.status)}</div><div className="text-xs text-muted-foreground">{format(encounter.visitDate)} · Dr. {encounter.doctor.name}</div></div>{canSign && ['DRAFT', 'COMPLETED'].includes(encounter.status) ? <Button disabled={sign.isPending} onClick={() => sign.mutate(encounter.id)}><FileLock2 className="size-4" />Sign & lock</Button> : null}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Detail title="Chief complaint" value={encounter.chiefComplaint} /><Detail title="Diagnosis" value={encounter.diagnosis} /><Detail title="Assessment" value={encounter.assessment} /><Detail title="Plan" value={encounter.treatmentAdvised || encounter.followUpPlan} /></div>{encounter.addendums.map((item) => <div key={item.id} className="mt-3 rounded bg-muted p-3 text-sm"><strong>Addendum · {item.author.name}</strong><div>{item.content}</div><div className="text-xs text-muted-foreground">{format(item.createdAt)}</div></div>)}{canSign && ['LOCKED', 'ADDENDUM_ADDED', 'SIGNED'].includes(encounter.status) ? <Button className="mt-3" variant="secondary" onClick={() => { const content = window.prompt('Addendum text'); if (content) addendum.mutate({ id: encounter.id, content }); }}>Add addendum</Button> : null}</Card>)} />;
}

function Prescriptions({ patient, canSign, onCreate, invalidate }: { patient: Patient360; canSign: boolean; onCreate: () => void; invalidate: () => void }) {
  const sign = useMutation({ mutationFn: (id: string) => apiRequest(`/clinical/prescriptions/${id}/sign`, { method: 'POST', body: '{}' }), onSuccess: invalidate });
  const pdf = useMutation({ mutationFn: (id: string) => apiBlob(`/clinical/prescriptions/${id}/pdf`), onSuccess: (blob) => { const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } });
  const prescriptions = patient.prescriptions ?? [];
  return <ListState empty="No prescriptions issued." action={canSign ? <Button onClick={onCreate}><Plus className="size-4" />New prescription</Button> : undefined} items={prescriptions.map((prescription) => <Card key={prescription.id} className="p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{prescription.prescriptionNo} · {label(prescription.status)}</div><div className="text-xs text-muted-foreground">{format(prescription.prescribedAt)} · Dr. {prescription.doctor.name}</div></div><div className="flex gap-2">{canSign && prescription.status === 'DRAFT' ? <Button disabled={sign.isPending} onClick={() => sign.mutate(prescription.id)}><FileLock2 className="size-4" />Sign</Button> : null}<Button variant="secondary" disabled={pdf.isPending} onClick={() => pdf.mutate(prescription.id)}>PDF</Button></div></div><div className="mt-3 space-y-2">{prescription.items.map((item) => <div key={item.id} className="rounded bg-muted p-3 text-sm"><strong>{item.medicineName} {item.strength}</strong><div>{item.dosage} · {item.frequency} · {item.duration}</div>{item.instructions ? <div className="text-muted-foreground">{item.instructions}</div> : null}</div>)}</div></Card>)} />;
}

function ClinicalComposer({ kind, patient, staff, resources, defaultDoctorId, onClose, onSaved }: { kind: 'encounter' | 'plan' | 'procedure' | 'prescription'; patient: Patient360; staff: StaffMember[]; resources: ClinicResource[]; defaultDoctorId?: string; onClose: () => void; onSaved: () => void }) {
  const [values, setValues] = useState<Record<string, string | boolean>>({ doctorId: defaultDoctorId ?? '', practitionerId: defaultDoctorId ?? staff[0]?.id ?? '', visitDate: nowLocal(), type: 'CONSULTATION', status: kind === 'procedure' ? 'COMPLETED' : 'DRAFT', consentVerified: false, plannedSessions: '1', prescribedAt: nowLocal() });
  const set = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  const mutation = useMutation({ mutationFn: async () => {
    if (kind === 'encounter') return apiRequest(`/clinical/patients/${patient.id}/encounters`, { method: 'POST', body: JSON.stringify({ branchId: patient.branchId, doctorId: values.doctorId, type: values.type, visitDate: values.visitDate, chiefComplaint: values.chiefComplaint, diagnosis: values.diagnosis, assessment: values.assessment, treatmentAdvised: values.treatmentAdvised, clinicalNotes: values.clinicalNotes, status: 'DRAFT' }) });
    if (kind === 'plan') return apiRequest(`/clinical/patients/${patient.id}/treatment-plans`, { method: 'POST', body: JSON.stringify({ branchId: patient.branchId, concern: values.concern, diagnosis: values.diagnosis, goals: values.goals, assignedDoctorId: values.doctorId, estimatedCost: values.estimatedCost || undefined, items: [{ name: values.itemName, plannedSessions: values.plannedSessions, frequency: values.frequency, estimatedAmount: values.itemAmount || undefined }] }) });
    if (kind === 'procedure') return apiRequest(`/clinical/patients/${patient.id}/procedure-sessions`, { method: 'POST', body: JSON.stringify({ branchId: patient.branchId, procedureName: values.procedureName, treatmentArea: values.treatmentArea, practitionerId: values.practitionerId, roomId: values.roomId || undefined, deviceId: values.deviceId || undefined, procedureNotes: values.procedureNotes, postCareInstructions: values.postCareInstructions, consentVerified: values.consentVerified, status: values.status, performedAt: values.status === 'COMPLETED' ? nowLocal() : undefined }) });
    return apiRequest(`/clinical/patients/${patient.id}/prescriptions`, { method: 'POST', body: JSON.stringify({ doctorId: values.doctorId, prescribedAt: values.prescribedAt, diagnosisSummary: values.diagnosis, instructions: values.instructions, precautions: values.precautions, items: [{ medicineName: values.medicineName, strength: values.strength, dosage: values.dosage, frequency: values.frequency, duration: values.duration, route: values.route, timing: values.timing, instructions: values.medicineInstructions }] }) });
  }, onSuccess: onSaved });
  const clinicians = staff.filter((member) => ['ADMIN', 'RECEPTIONIST'].includes(member.role)); const rooms = resources.filter((item) => item.type === 'ROOM'); const devices = resources.filter((item) => item.type === 'EQUIPMENT');
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><Card className="max-h-[90vh] w-full max-w-2xl overflow-y-auto"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">New {kind.replaceAll('_', ' ')}</h2><p className="text-sm text-muted-foreground">{patient.fullName} · {patient.patientNo}</p></div><Button variant="ghost" onClick={onClose}>Close</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">
    {(kind === 'encounter' || kind === 'plan' || kind === 'prescription') ? <Field label="Dr. Revive"><Select value={String(values.doctorId)} onChange={(event) => set('doctorId', event.target.value)}><option value="">Select Dr. Revive</option>{staff.filter((item) => item.role === 'ADMIN').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field> : null}
    {kind === 'encounter' ? <><Field label="Encounter type"><Select value={String(values.type)} onChange={(event) => set('type', event.target.value)}>{['CONSULTATION', 'VIDEO_CONSULTATION', 'FOLLOW_UP_CONSULTATION', 'PROCEDURE', 'TREATMENT_SESSION', 'REVIEW', 'EMERGENCY_REVIEW', 'OTHER'].map((item) => <option key={item}>{label(item)}</option>)}</Select></Field><Field label="Visit date"><Input type="datetime-local" value={String(values.visitDate)} onChange={(event) => set('visitDate', event.target.value)} /></Field><TextField label="Chief complaint" name="chiefComplaint" values={values} set={set} /><TextField label="Diagnosis" name="diagnosis" values={values} set={set} /><TextField label="Assessment" name="assessment" values={values} set={set} /><TextField label="Treatment advised" name="treatmentAdvised" values={values} set={set} /><Area label="Clinical notes" name="clinicalNotes" values={values} set={set} /></> : null}
    {kind === 'plan' ? <><TextField label="Concern" name="concern" values={values} set={set} /><TextField label="Diagnosis" name="diagnosis" values={values} set={set} /><TextField label="Goals" name="goals" values={values} set={set} /><TextField label="Estimated cost" name="estimatedCost" values={values} set={set} type="number" /><TextField label="Plan item / service" name="itemName" values={values} set={set} /><TextField label="Planned sessions" name="plannedSessions" values={values} set={set} type="number" /><TextField label="Frequency" name="frequency" values={values} set={set} /><TextField label="Item amount" name="itemAmount" values={values} set={set} type="number" /></> : null}
    {kind === 'procedure' ? <><Field label="Practitioner"><Select value={String(values.practitionerId)} onChange={(event) => set('practitionerId', event.target.value)}>{clinicians.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><TextField label="Procedure" name="procedureName" values={values} set={set} /><TextField label="Treatment area" name="treatmentArea" values={values} set={set} /><Field label="Room"><Select value={String(values.roomId ?? '')} onChange={(event) => set('roomId', event.target.value)}><option value="">Not selected</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Device"><Select value={String(values.deviceId ?? '')} onChange={(event) => set('deviceId', event.target.value)}><option value="">Not selected</option>{devices.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Status"><Select value={String(values.status)} onChange={(event) => set('status', event.target.value)}>{['PLANNED', 'READY', 'IN_PROGRESS', 'COMPLETED'].map((item) => <option key={item}>{label(item)}</option>)}</Select></Field><Area label="Procedure notes" name="procedureNotes" values={values} set={set} /><Area label="Post-care instructions" name="postCareInstructions" values={values} set={set} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(values.consentVerified)} onChange={(event) => set('consentVerified', event.target.checked)} />Consent verified</label></> : null}
    {kind === 'prescription' ? <><Field label="Prescription date"><Input type="datetime-local" value={String(values.prescribedAt)} onChange={(event) => set('prescribedAt', event.target.value)} /></Field><TextField label="Diagnosis" name="diagnosis" values={values} set={set} /><TextField label="Medicine" name="medicineName" values={values} set={set} /><TextField label="Strength" name="strength" values={values} set={set} /><TextField label="Dosage" name="dosage" values={values} set={set} /><TextField label="Frequency" name="frequency" values={values} set={set} /><TextField label="Duration" name="duration" values={values} set={set} /><TextField label="Route" name="route" values={values} set={set} /><TextField label="Timing" name="timing" values={values} set={set} /><Area label="Medicine instructions" name="medicineInstructions" values={values} set={set} /><Area label="General instructions" name="instructions" values={values} set={set} /><Area label="Precautions" name="precautions" values={values} set={set} /></> : null}
  </div>{mutation.isError ? <p className="mt-3 text-sm text-red-700">{mutation.error.message}</p> : null}<div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? 'Saving…' : 'Save'}</Button></div></Card></div>;
}
function Field({ label: title, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-sm"><span className="font-medium">{title}</span>{children}</label>; }
function TextField({ label: title, name, values, set, type = 'text' }: { label: string; name: string; values: Record<string, string | boolean>; set: (name: string, value: string) => void; type?: string }) { return <Field label={title}><Input type={type} value={String(values[name] ?? '')} onChange={(event) => set(name, event.target.value)} /></Field>; }
function Area({ label: title, name, values, set }: { label: string; name: string; values: Record<string, string | boolean>; set: (name: string, value: string) => void }) { return <label className="grid gap-1 text-sm sm:col-span-2"><span className="font-medium">{title}</span><textarea className="min-h-24 rounded-md border border-border bg-surface px-3 py-2" value={String(values[name] ?? '')} onChange={(event) => set(name, event.target.value)} /></label>; }
