'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, FileCheck2, ImagePlus, Upload } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { SignaturePad } from '@/components/ui/signature-pad';
import { apiAssetUrl, apiBlob, apiRequest } from '@/services/api';
import type { Patient360 } from '@/types/clinical';
import type { ConsentRecord, ConsentTemplate, FormField, FormSubmission, FormTemplate, SecurePatientFile } from '@/types/forms';
import type { StaffMember } from '@/types/front-desk';

const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
const format = (value?: string | null) => value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '—';

export function PatientFormsPanel({ patient }: { patient: Patient360 }) {
  const client = useQueryClient(); const [formTemplateId, setFormTemplateId] = useState(''); const [formValues, setFormValues] = useState<Record<string, unknown>>({});
  const [consentTemplateId, setConsentTemplateId] = useState(''); const [signerName, setSignerName] = useState(patient.fullName); const [signature, setSignature] = useState(''); const [guardianName, setGuardianName] = useState(''); const [guardianSignature, setGuardianSignature] = useState(''); const [witnessId, setWitnessId] = useState('');
  const forms = useQuery({ queryKey: ['patient-form-templates', patient.branchId], queryFn: () => apiRequest<{ data: FormTemplate[] }>(`/forms/templates?branchId=${patient.branchId}&status=PUBLISHED`) });
  const submissions = useQuery({ queryKey: ['patient-form-submissions', patient.id], queryFn: () => apiRequest<{ data: FormSubmission[] }>(`/forms/patients/${patient.id}/submissions`) });
  const consentTemplates = useQuery({ queryKey: ['patient-consent-templates', patient.branchId], queryFn: () => apiRequest<{ data: ConsentTemplate[] }>(`/consents/templates?branchId=${patient.branchId}`) });
  const records = useQuery({ queryKey: ['patient-consents', patient.id], queryFn: () => apiRequest<{ data: ConsentRecord[] }>(`/consents/patients/${patient.id}`) });
  const staff = useQuery({ queryKey: ['consent-witnesses', patient.branchId], queryFn: () => apiRequest<{ data: StaffMember[] }>(`/front-desk/staff?branchId=${patient.branchId}`) });
  const selectedForm = forms.data?.data.find((item) => item.id === formTemplateId); const selectedConsent = consentTemplates.data?.data.find((item) => item.id === consentTemplateId && item.status === 'PUBLISHED');
  const submit = useMutation({ mutationFn: () => apiRequest('/forms/submissions', { method: 'POST', body: JSON.stringify({ templateId: formTemplateId, patientId: patient.id, values: formValues }) }), onSuccess: () => { setFormTemplateId(''); setFormValues({}); client.invalidateQueries({ queryKey: ['patient-form-submissions', patient.id] }); } });
  const sign = useMutation({ mutationFn: () => apiRequest('/consents/sign', { method: 'POST', body: JSON.stringify({ templateId: consentTemplateId, patientId: patient.id, signerName, signatureBase64: signature, guardianName: guardianName || undefined, guardianRelationship: guardianName ? 'Guardian' : undefined, guardianSignatureBase64: guardianSignature || undefined, staffWitnessId: witnessId || undefined }) }), onSuccess: () => { setConsentTemplateId(''); setSignature(''); setGuardianSignature(''); client.invalidateQueries({ queryKey: ['patient-consents', patient.id] }); client.invalidateQueries({ queryKey: ['patient-360', patient.id] }); } });
  const withdraw = useMutation({ mutationFn: ({ id, reason }: { id: string; reason: string }) => apiRequest(`/consents/${id}/withdraw`, { method: 'POST', body: JSON.stringify({ reason }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['patient-consents', patient.id] }); client.invalidateQueries({ queryKey: ['patient-360', patient.id] }); } });
  const pdf = useMutation({ mutationFn: (id: string) => apiBlob(`/consents/${id}/pdf`), onSuccess: (blob) => { const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } });
  return <div className="grid gap-4 xl:grid-cols-2"><Card><h2 className="font-semibold">Complete a form</h2><Select className="mt-3" value={formTemplateId} onChange={(event) => { setFormTemplateId(event.target.value); setFormValues({}); }}><option value="">Choose published form</option>{forms.data?.data.map((template) => <option key={template.id} value={template.id}>{template.name} · v{template.currentVersion}</option>)}</Select>{selectedForm ? <div className="mt-4 space-y-3">{selectedForm.fields.filter((field) => isVisible(field, formValues)).map((field) => <DynamicField key={field.key} field={field} value={formValues[field.key]} onChange={(value) => setFormValues((current) => ({ ...current, [field.key]: value }))} />)}{submit.isError ? <ErrorText text={submit.error.message} /> : null}<Button className="w-full" disabled={submit.isPending} onClick={() => submit.mutate()}>{submit.isPending ? 'Submitting…' : 'Submit versioned form'}</Button></div> : null}<div className="mt-5 border-t pt-4"><h3 className="text-sm font-semibold">Submission history</h3><History empty="No forms submitted." items={(submissions.data?.data ?? []).map((item) => <div key={item.id}><div className="font-medium">{item.template.name}</div><div className="text-xs text-muted-foreground">{format(item.submittedAt)} · {label(item.status)}</div></div>)} /></div></Card>
    <Card><h2 className="font-semibold">Capture consent</h2><Select className="mt-3" value={consentTemplateId} onChange={(event) => { setConsentTemplateId(event.target.value); setSignature(''); }}><option value="">Choose published consent</option>{consentTemplates.data?.data.filter((item) => item.status === 'PUBLISHED').map((template) => <option key={template.id} value={template.id}>{template.name} · v{template.currentVersion}</option>)}</Select>{selectedConsent ? <div className="mt-4 space-y-3"><div className="max-h-40 overflow-y-auto rounded-md bg-muted p-3 text-sm whitespace-pre-wrap">{selectedConsent.consentText}</div><Input value={signerName} onChange={(event) => setSignerName(event.target.value)} placeholder="Signer name" /><SignaturePad onChange={setSignature} />{selectedConsent.requiresGuardian ? <><Input placeholder="Guardian name" value={guardianName} onChange={(event) => setGuardianName(event.target.value)} /><SignaturePad onChange={setGuardianSignature} /></> : null}{selectedConsent.requiresWitness ? <Select value={witnessId} onChange={(event) => setWitnessId(event.target.value)}><option value="">Select staff witness</option>{staff.data?.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select> : null}{sign.isError ? <ErrorText text={sign.error.message} /> : null}<Button className="w-full" disabled={!signature || sign.isPending} onClick={() => sign.mutate()}>{sign.isPending ? 'Generating signed PDF…' : 'Sign consent'}</Button></div> : null}<div className="mt-5 border-t pt-4"><h3 className="text-sm font-semibold">Consent history</h3><History empty="No consent records." items={(records.data?.data ?? []).map((record) => <div key={record.id} className="flex items-start justify-between gap-2"><div><div className="font-medium">{record.template.name} · v{record.templateVersion}</div><div className="text-xs text-muted-foreground">{format(record.signedAt)} · {label(record.status)}</div>{record.withdrawalReason ? <div className="text-xs text-red-700">{record.withdrawalReason}</div> : null}</div><div className="flex gap-1"><Button className="h-8 px-2 text-xs" variant="secondary" onClick={() => pdf.mutate(record.id)}>PDF</Button>{record.status === 'SIGNED' ? <Button className="h-8 px-2 text-xs" variant="ghost" onClick={() => { const reason = window.prompt('Withdrawal reason'); if (reason) withdraw.mutate({ id: record.id, reason }); }}>Withdraw</Button> : null}</div></div>)} /></div></Card></div>;
}

function isVisible(field: FormField, values: Record<string, unknown>) { if (field.hidden) return false; const condition = (field as FormField & { condition?: { field: string; operator: string; value: unknown } }).condition; if (!condition) return true; const actual = values[condition.field]; if (condition.operator === 'EQUALS') return actual === condition.value; if (condition.operator === 'NOT_EQUALS') return actual !== condition.value; return String(actual ?? '').includes(String(condition.value ?? '')); }
function DynamicField({ field, value, onChange }: { field: FormField; value: unknown; onChange: (value: unknown) => void }) { if (field.type === 'SIGNATURE') return <label className="grid gap-1 text-sm"><span className="font-medium">{field.label}{field.required ? ' *' : ''}</span><SignaturePad onChange={onChange} /></label>; if (field.type === 'CHECKBOX' || field.type === 'DECLARATION') return <label className="flex gap-2 text-sm"><input type="checkbox" checked={Boolean(value)} disabled={field.readOnly} onChange={(event) => onChange(event.target.checked)} />{field.label}{field.required ? ' *' : ''}</label>; if (field.type === 'DROPDOWN' || field.type === 'RADIO') return <label className="grid gap-1 text-sm"><span className="font-medium">{field.label}</span><Select disabled={field.readOnly} value={String(value ?? '')} onChange={(event) => onChange(event.target.value)}><option value="">Select</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</Select></label>; return <label className="grid gap-1 text-sm"><span className="font-medium">{field.label}{field.required ? ' *' : ''}</span><Input type={field.type === 'NUMBER' ? 'number' : field.type === 'DATE' ? 'date' : 'text'} readOnly={field.readOnly} placeholder={field.placeholder ?? undefined} value={String(value ?? '')} onChange={(event) => onChange(event.target.value)} /></label>; }

export function PatientGalleryPanel({ patient }: { patient: Patient360 }) {
  const client = useQueryClient(); const [upload, setUpload] = useState({ fileType: 'BEFORE_IMAGE', photoAngle: 'FRONT', treatmentArea: '', annotation: '', marketingPermission: false }); const [file, setFile] = useState<File | null>(null); const [beforeId, setBeforeId] = useState(''); const [afterId, setAfterId] = useState('');
  const files = useQuery({ queryKey: ['patient-gallery', patient.id], queryFn: () => apiRequest<{ data: SecurePatientFile[] }>(`/files?patientId=${patient.id}&gallery=true`) }); const images = files.data?.data ?? []; const before = images.find((item) => item.id === beforeId); const after = images.find((item) => item.id === afterId);
  const mutation = useMutation({ mutationFn: async () => { if (!file) throw new Error('Choose an image'); return apiRequest('/files', { method: 'POST', body: JSON.stringify({ patientId: patient.id, fileType: upload.fileType, originalFilename: file.name, mimeType: file.type, contentBase64: await fileData(file), clinicalUsePermission: true, marketingPermission: upload.marketingPermission, visibility: 'CLINICAL_ONLY', photoAngle: upload.photoAngle, treatmentArea: upload.treatmentArea || undefined, visitDate: new Date().toISOString(), annotation: upload.annotation ? { note: upload.annotation } : undefined }) }); }, onSuccess: () => { setFile(null); client.invalidateQueries({ queryKey: ['patient-gallery', patient.id] }); } });
  return <div className="space-y-4"><Card><h2 className="font-semibold">Upload original clinical image</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><Select value={upload.fileType} onChange={(event) => setUpload({ ...upload, fileType: event.target.value })}><option value="BEFORE_IMAGE">Before image</option><option value="AFTER_IMAGE">After image</option><option value="CLINICAL_PHOTOGRAPH">Clinical photograph</option></Select><Select value={upload.photoAngle} onChange={(event) => setUpload({ ...upload, photoAngle: event.target.value })}>{['FRONT', 'LEFT', 'RIGHT', 'CLOSE_UP', 'TREATMENT_AREA', 'OTHER'].map((item) => <option key={item}>{label(item)}</option>)}</Select><Input placeholder="Treatment area" value={upload.treatmentArea} onChange={(event) => setUpload({ ...upload, treatmentArea: event.target.value })} /><Input className="lg:col-span-2" placeholder="Annotation / clinical note" value={upload.annotation} onChange={(event) => setUpload({ ...upload, annotation: event.target.value })} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={upload.marketingPermission} onChange={(event) => setUpload({ ...upload, marketingPermission: event.target.checked })} />Approved for marketing use</label><Button disabled={!file || mutation.isPending} onClick={() => mutation.mutate()}><ImagePlus className="size-4" />Upload securely</Button></div>{mutation.isError ? <ErrorText text={mutation.error.message} /> : null}</Card>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{images.map((image) => <Card key={image.id} className="overflow-hidden p-0"><img src={apiAssetUrl(image.accessUrl)} alt={image.originalFilename ?? image.name} className="aspect-[4/3] w-full object-cover" /><div className="p-3"><div className="font-medium">{label(image.fileType)} · {label(image.photoAngle ?? 'OTHER')}</div><div className="text-xs text-muted-foreground">{format(image.visitDate ?? image.createdAt)} · {image.treatmentArea ?? 'Area not specified'}</div>{image.annotation?.note ? <p className="mt-2 text-sm">{String(image.annotation.note)}</p> : null}<div className="mt-2 text-xs">Clinical: {image.clinicalUsePermission ? 'Yes' : 'No'} · Marketing: {image.marketingPermission ? 'Yes' : 'No'}</div></div></Card>)}</div>{!images.length ? <Card className="py-10 text-center text-sm text-muted-foreground">No clinical photographs recorded.</Card> : null}
    {images.length ? <Card><h2 className="font-semibold">Before-and-after comparison</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Select value={beforeId} onChange={(event) => setBeforeId(event.target.value)}><option value="">Choose before image</option>{images.filter((item) => item.fileType === 'BEFORE_IMAGE').map((item) => <option key={item.id} value={item.id}>{item.originalFilename} · {format(item.visitDate)}</option>)}</Select><Select value={afterId} onChange={(event) => setAfterId(event.target.value)}><option value="">Choose after image</option>{images.filter((item) => item.fileType === 'AFTER_IMAGE').map((item) => <option key={item.id} value={item.id}>{item.originalFilename} · {format(item.visitDate)}</option>)}</Select></div>{before && after ? <><div className="mt-4 grid grid-cols-2 gap-2"><ComparisonImage title="Before" file={before} /><ComparisonImage title="After" file={after} /></div><Button className="mt-3" variant="secondary" onClick={() => exportComparison(before, after)}><Download className="size-4" />Export watermarked comparison</Button></> : null}</Card> : null}</div>;
}

export function PatientDocumentsPanel({ patient }: { patient: Patient360 }) {
  const client = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [fileType, setFileType] = useState('MEDICAL_REPORT'); const files = useQuery({ queryKey: ['secure-patient-files', patient.id], queryFn: () => apiRequest<{ data: SecurePatientFile[] }>(`/files?patientId=${patient.id}`) });
  const upload = useMutation({ mutationFn: async () => { if (!file) throw new Error('Choose a document'); return apiRequest('/files', { method: 'POST', body: JSON.stringify({ patientId: patient.id, fileType, originalFilename: file.name, mimeType: file.type, contentBase64: await fileData(file), clinicalUsePermission: fileType !== 'INVOICE', marketingPermission: false, visibility: fileType === 'INVOICE' || fileType === 'PAYMENT_RECEIPT' ? 'ADMINISTRATIVE' : 'CARE_TEAM' }) }); }, onSuccess: () => { setFile(null); client.invalidateQueries({ queryKey: ['secure-patient-files', patient.id] }); } });
  return <div className="space-y-4"><Card><div className="grid gap-3 sm:grid-cols-[1fr_220px_auto]"><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><Select value={fileType} onChange={(event) => setFileType(event.target.value)}>{['MEDICAL_REPORT', 'PRESCRIPTION', 'CONSENT', 'INVOICE', 'PAYMENT_RECEIPT', 'IDENTITY_DOCUMENT', 'OTHER_DOCUMENT'].map((item) => <option key={item}>{label(item)}</option>)}</Select><Button disabled={!file || upload.isPending} onClick={() => upload.mutate()}><Upload className="size-4" />Upload securely</Button></div>{upload.isError ? <ErrorText text={upload.error.message} /> : null}</Card><Card><div className="space-y-2">{files.data?.data.filter((item) => !['CLINICAL_PHOTOGRAPH', 'BEFORE_IMAGE', 'AFTER_IMAGE'].includes(item.fileType)).map((item) => <a key={item.id} href={apiAssetUrl(item.accessUrl)} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-md border p-3 hover:bg-muted"><div><div className="font-medium">{item.originalFilename ?? item.name}</div><div className="text-xs text-muted-foreground">{label(item.fileType)} · {format(item.createdAt)} · {item.visibility.replaceAll('_', ' ')}</div></div><FileCheck2 className="size-5 text-primary" /></a>)}{!files.data?.data.length ? <div className="py-8 text-center text-sm text-muted-foreground">No secure documents.</div> : null}</div></Card></div>;
}

function History({ items, empty }: { items: React.ReactNode[]; empty: string }) { return <div className="mt-2 space-y-2 text-sm">{items.length ? items.map((item, index) => <div key={index} className="rounded-md border p-3">{item}</div>) : <p className="py-4 text-center text-muted-foreground">{empty}</p>}</div>; }
function ErrorText({ text }: { text: string }) { return <p className="mt-2 text-sm text-red-700">{text}</p>; }
function fileData(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }
function ComparisonImage({ title, file }: { title: string; file: SecurePatientFile }) { return <div className="relative overflow-hidden rounded-md border"><img src={apiAssetUrl(file.accessUrl)} alt={title} className="aspect-[4/3] w-full object-cover" /><span className="absolute left-2 top-2 rounded bg-black/70 px-2 py-1 text-xs text-white">{title}</span></div>; }
async function exportComparison(before: SecurePatientFile, after: SecurePatientFile) { const load = (url: string) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.crossOrigin = 'anonymous'; image.onload = () => resolve(image); image.onerror = reject; image.src = apiAssetUrl(url); }); const [beforeImage, afterImage] = await Promise.all([load(before.accessUrl), load(after.accessUrl)]); const canvas = document.createElement('canvas'); canvas.width = 1600; canvas.height = 700; const context = canvas.getContext('2d'); if (!context) return; context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(beforeImage, 0, 0, 800, 600); context.drawImage(afterImage, 800, 0, 800, 600); context.fillStyle = '#a51d2d'; context.font = 'bold 28px sans-serif'; context.fillText('BEFORE', 24, 646); context.fillText('AFTER', 824, 646); context.globalAlpha = 0.25; context.font = 'bold 42px sans-serif'; context.fillText('REVIVE CLINIC • CLINICAL COPY', 420, 340); const link = document.createElement('a'); link.download = `comparison-${before.id}-${after.id}.png`; link.href = canvas.toDataURL('image/png'); link.click(); }
