import { Router } from 'express';
import { inventoryController } from '../controllers/inventory.controller.js';
import { requireAuth } from '../middleware/auth.js';

export const inventoryRoutes = Router();
inventoryRoutes.use(requireAuth);
inventoryRoutes.get('/products', (req, res, next) => { inventoryController.listProducts(req, res).catch(next); });
inventoryRoutes.post('/products', (req, res, next) => { inventoryController.createProduct(req, res).catch(next); });
inventoryRoutes.patch('/products/:id', (req, res, next) => { inventoryController.updateProduct(req, res).catch(next); });
inventoryRoutes.get('/vendors', (req, res, next) => { inventoryController.listVendors(req, res).catch(next); });
inventoryRoutes.post('/vendors', (req, res, next) => { inventoryController.createVendor(req, res).catch(next); });
inventoryRoutes.patch('/vendors/:id', (req, res, next) => { inventoryController.updateVendor(req, res).catch(next); });
inventoryRoutes.get('/stock', (req, res, next) => { inventoryController.listStock(req, res).catch(next); });
inventoryRoutes.get('/batches', (req, res, next) => { inventoryController.listBatches(req, res).catch(next); });
inventoryRoutes.get('/movements', (req, res, next) => { inventoryController.listMovements(req, res).catch(next); });
inventoryRoutes.post('/movements/:id/reverse', (req, res, next) => { inventoryController.reverseMovement(req, res).catch(next); });
inventoryRoutes.get('/procedure-consumables/config', (req, res, next) => { inventoryController.listConfigs(req, res).catch(next); });
inventoryRoutes.post('/procedure-consumables/config', (req, res, next) => { inventoryController.saveConfig(req, res).catch(next); });
inventoryRoutes.get('/procedure-consumptions', (req, res, next) => { inventoryController.listConsumptions(req, res).catch(next); });
inventoryRoutes.post('/procedure-consumptions/stage/:procedureSessionId', (req, res, next) => { inventoryController.stageConsumption(req, res).catch(next); });
inventoryRoutes.post('/procedure-consumptions/:id/confirm', (req, res, next) => { inventoryController.confirmConsumption(req, res).catch(next); });
inventoryRoutes.get('/purchase-orders', (req, res, next) => { inventoryController.listPurchaseOrders(req, res).catch(next); });
inventoryRoutes.post('/purchase-orders', (req, res, next) => { inventoryController.createPurchaseOrder(req, res).catch(next); });
inventoryRoutes.post('/purchase-orders/:id/actions', (req, res, next) => { inventoryController.purchaseOrderAction(req, res).catch(next); });
inventoryRoutes.get('/goods-receipts', (req, res, next) => { inventoryController.listGoodsReceipts(req, res).catch(next); });
inventoryRoutes.post('/goods-receipts', (req, res, next) => { inventoryController.createGoodsReceipt(req, res).catch(next); });
inventoryRoutes.get('/transfers', (req, res, next) => { inventoryController.listTransfers(req, res).catch(next); });
inventoryRoutes.post('/transfers', (req, res, next) => { inventoryController.createTransfer(req, res).catch(next); });
inventoryRoutes.post('/transfers/:id/actions', (req, res, next) => { inventoryController.transferAction(req, res).catch(next); });
inventoryRoutes.post('/adjustments', (req, res, next) => { inventoryController.createAdjustment(req, res).catch(next); });
inventoryRoutes.get('/alerts', (req, res, next) => { inventoryController.listAlerts(req, res).catch(next); });
inventoryRoutes.patch('/alerts/:id', (req, res, next) => { inventoryController.updateAlert(req, res).catch(next); });
