ALTER TYPE "EnquirySource" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS';
ALTER TYPE "EnquirySource" ADD VALUE IF NOT EXISTS 'META_ADS';

ALTER TABLE "ClinicSettings"
ADD COLUMN IF NOT EXISTS "clinicEmail" TEXT,
ADD COLUMN IF NOT EXISTS "clinicLogoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "gstPercent" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "invoiceTerms" TEXT,
ADD COLUMN IF NOT EXISTS "invoiceSignature" TEXT,
ADD COLUMN IF NOT EXISTS "invoiceFooter" TEXT,
ADD COLUMN IF NOT EXISTS "paymentInstructions" TEXT,
ADD COLUMN IF NOT EXISTS "qrRegistrationEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "patientFormConfig" JSONB,
ADD COLUMN IF NOT EXISTS "whatsappAccessToken" TEXT;
