'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { apiRequest } from '@/services/api';
import { useSessionStore } from '@/store/session-store';
import type { Person } from '@/types/foundation';
import type { ClinicService, WaitlistEntry } from '@/types/front-desk';

export function WaitlistView() {
  const client = useQueryClient(); const { selectedBranchId } = useSessionStore();
  const [form, setForm] = useState({ personId: '', serviceId: '', requestedService: '', preferredFrom: '', preferredTo: '', priority: 'MEDIUM' });
  const [bookingAt, setBookingAt] = useState('');
  const people = useQuery({ queryKey: ['people-select'], queryFn: () => apiRequest<{ data: Person[] }>('/people?take=200') });
  const services = useQuery({ queryKey: ['front-desk-services', selectedBranchId], queryFn: () => apiRequest<{ data: ClinicService[] }>(`/front-desk/services?branchId=${selectedBranchId}`), enabled: Boolean(selectedBranchId) });
  const entries = useQuery({ queryKey: ['waitlist', selectedBranchId], queryFn: () => apiRequest<{ data: WaitlistEntry[] }>(`/waitlist?branchId=${selectedBranchId}`), enabled: Boolean(selectedBranchId) });
  const create = useMutation({ mutationFn: () => apiRequest('/waitlist', { method: 'POST', body: JSON.stringify({ ...form, branchId: selectedBranchId, serviceId: form.serviceId || undefined }) }), onSuccess: () => { setForm({ personId: '', serviceId: '', requestedService: '', preferredFrom: '', preferredTo: '', priority: 'MEDIUM' }); client.invalidateQueries({ queryKey: ['waitlist'] }); } });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => apiRequest(`/waitlist/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['waitlist'] }) });
  const book = useMutation({ mutationFn: (id: string) => apiRequest(`/waitlist/${id}/book`, { method: 'POST', body: JSON.stringify({ appointmentAt: bookingAt }) }), onSuccess: () => { setBookingAt(''); client.invalidateQueries({ queryKey: ['waitlist'] }); client.invalidateQueries({ queryKey: ['appointments'] }); } });
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <section className="space-y-5"><div><h1 className="text-2xl font-semibold">Waitlist</h1><p className="text-sm text-muted-foreground">Match patients to newly available services, practitioners, and time windows.</p></div>
    <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Card><h2 className="font-semibold">Add to waitlist</h2><div className="mt-4 space-y-3"><Select value={form.personId} onChange={(event) => set('personId', event.target.value)}><option value="">Select person</option>{people.data?.data.map((person) => <option key={person.id} value={person.id}>{person.fullName} · {person.primaryMobile}</option>)}</Select><Select value={form.serviceId} onChange={(event) => { const service = services.data?.data.find((item) => item.id === event.target.value); setForm((current) => ({ ...current, serviceId: event.target.value, requestedService: service?.name ?? current.requestedService })); }}><option value="">Select configured service</option>{services.data?.data.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</Select><Input placeholder="Requested service" value={form.requestedService} onChange={(event) => set('requestedService', event.target.value)} /><label className="block text-xs text-muted-foreground">Preferred from<Input className="mt-1" type="datetime-local" value={form.preferredFrom} onChange={(event) => set('preferredFrom', event.target.value)} /></label><label className="block text-xs text-muted-foreground">Preferred until<Input className="mt-1" type="datetime-local" value={form.preferredTo} onChange={(event) => set('preferredTo', event.target.value)} /></label><Select value={form.priority} onChange={(event) => set('priority', event.target.value)}><option value="LOW">Low priority</option><option value="MEDIUM">Medium priority</option><option value="HIGH">High priority</option><option value="URGENT">Urgent</option></Select>{create.isError ? <p className="text-sm text-red-600">{create.error.message}</p> : null}<Button className="w-full" disabled={!selectedBranchId || !form.personId || !form.requestedService || !form.preferredFrom || !form.preferredTo || create.isPending} onClick={() => create.mutate()}>Add entry</Button></div></Card>
    <Card className="overflow-hidden p-0">{entries.isLoading ? <State text="Loading waitlist…" /> : entries.isError ? <State text="Waitlist could not be loaded." /> : (entries.data?.data.length ?? 0) === 0 ? <State text="No waitlist entries for this branch." /> : <div className="divide-y">{entries.data?.data.map((entry) => <article key={entry.id} className="p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-medium">{entry.person.fullName}</div><div className="text-sm text-muted-foreground">{entry.requestedService} · {new Date(entry.preferredFrom).toLocaleDateString()}–{new Date(entry.preferredTo).toLocaleDateString()}</div><div className="mt-1 text-xs text-muted-foreground">{entry.priority} · {entry.status}</div></div><div className="flex flex-wrap items-center gap-2">{entry.status === 'ACTIVE' ? <Button variant="secondary" onClick={() => update.mutate({ id: entry.id, status: 'NOTIFIED' })}>Mark notified</Button> : null}{entry.status === 'NOTIFIED' ? <Button variant="secondary" onClick={() => update.mutate({ id: entry.id, status: 'ACCEPTED' })}>Accepted</Button> : null}{['ACTIVE', 'NOTIFIED', 'ACCEPTED'].includes(entry.status) ? <><Input className="w-52" type="datetime-local" value={bookingAt} onChange={(event) => setBookingAt(event.target.value)} /><Button disabled={!bookingAt || book.isPending} onClick={() => book.mutate(entry.id)}>Book slot</Button></> : null}</div></div></article>)}</div>}</Card></div>
  </section>;
}
function State({ text }: { text: string }) { return <div className="p-10 text-center text-sm text-muted-foreground">{text}</div>; }

